meroxa/cli

- .github/workflows/pull_request.yml
*Fixes github actions secrets to the correct values for acceptance testing*
*Provide link:*
> Fix Github Action secret naming

- .github/workflows/release.yml
- .goreleaser.yml
Goreleaser provides a homebrew plugin so brew versiona are automatically updated with each release: https://goreleaser.com/customization/homebrew/.
This PR aims to take advantage of that.
Fixes https://meroxa.atlassian.net/browse/PLATFORM-239
> chore(cli): Add brew to goreleaser

- cmd/connect.go
Fixes output of `meroxa connect`
> fix(connect): Output

- cmd/login.go
- cmd/logout.go
There were some inconsistencies that I think were easy to fix.
The copy changes on `logout` are to match what we're currently showing when logging in:
```
❯ .m login
Successfully logged in.
```
**Before**
```
❯ .m logout
credentials cleared
```
**Now**
```
❯ .m logout
Successfully logged out.
```
> feat(auth): Minor changes on auth flow

- cmd/remove_connector.go
- cmd/remove_connector_test.go
*A brief description of the change, what it is and why it was made.*
Fixes https://meroxa.atlassian.net/browse/PLATFORM-374
**Before**
```
❯ .m remove connector my-connector
Removing ...
To proceed, type "" or re-run this command with --force
▸ ^C
```
**Now**
```
❯ .m remove connector my-connector
Removing my-connector...
To proceed, type "my-connector" or re-run this command with --force
▸ ^C
```
> fix(remove): Connector message

- utils/display.go
Column order is now consistent for different entities.
> Make sure column order is consistent

- cmd/list.go
- cmd/list_connectors.go
- cmd/list_connectors_test.go
- cmd/remove_connector_test.go
- docs/cmd/meroxa_list_connectors.md
- go.mod
- go.sum
- mock-cmd/list_connectors.go
- utils/tests.go
- vendor/github.com/meroxa/meroxa-go/connector.go
- vendor/modules.txt
Fixes https://meroxa.atlassian.net/browse/PLATFORM-339
~It depends on https://github.com/meroxa/meroxa-go/pull/29~
```
❯ .m list connectors
. ID        NAME          TYPE                   STREAMS                STATE    PIPELINE
===== ============== ============= ================================= ========= ==========
255   my-connector   jdbc-source   output:                           running   11
resource-149-499379-public.User
❯ .m list pipelines
ID        NAME         STATE
==== ================ =========
9       m-demo       healthy
10   empty-pipeline   healthy
11      default       healthy
❯ .m list connectors --pipeline default
ID        NAME          TYPE                   STREAMS                STATE    PIPELINE
===== ============== ============= …
```
> [PLATFORM-339] feat(list): Connectors by pipeline

- cmd/remove.go
- cmd/remove_test.go
Adds a little easter egg...
```
❯ .m list pipelines
ID        NAME         STATE
==== ================ =========
9       m-demo       healthy
10   empty-pipeline   healthy
11      default       healthy
❯ .m remove pipeline empty-pipeline --yolo
Removing empty-pipeline...
pipeline empty-pipeline successfully removed
```
> feat(remove): Add --yolo (hidden) flag 😜

- go.mod
- go.sum
- utils/display.go
- vendor/github.com/meroxa/meroxa-go/connector.go
- vendor/modules.txt
Fixes https://meroxa.atlassian.net/browse/PLATFORM-402
Shows pipeline name instead of an id.
~Depends on https://github.com/meroxa/meroxa-go/pull/30~
```
❯ .m list connectors
ID         NAME           TYPE                   STREAMS                STATE    PIPELINE
===== ================ ============= ================================= ========= ==========
460   my-connector-2   jdbc-source   output:                           pending   default
resource-420-954565-public.User
```
> [PLATFORM-402] feat(list): Show pipeline name on connectors list

- cmd/open_billing.go
Updated the billing URL to point to the right location
Fixes <JIRA Issue>
*Provide link:*
> Update billing URL

- cmd/meroxa/root/resources/create.go
- cmd/meroxa/root/resources/create_test.go
- cmd/meroxa/root/resources/resources.go
- cmd/meroxa/root/resources/rotate_tunnel_key.go
- cmd/meroxa/root/resources/rotate_tunnel_key_test.go
- cmd/meroxa/root/resources/update.go
- cmd/meroxa/root/resources/update_test.go
- cmd/meroxa/root/resources/validate.go
- cmd/meroxa/root/resources/validate_test.go
- docs/cmd/md/meroxa_resources.md
- docs/cmd/md/meroxa_resources_create.md
- docs/cmd/md/meroxa_resources_rotate-tunnel-key.md
- docs/cmd/md/meroxa_resources_update.md
- docs/cmd/md/meroxa_resources_validate.md
- docs/cmd/www/meroxa-resources-create.md
- docs/cmd/www/meroxa-resources-rotate-tunnel-key.md
- docs/cmd/www/meroxa-resources-update.md
- docs/cmd/www/meroxa-resources-validate.md
- docs/cmd/www/meroxa-resources.md
- etc/completion/meroxa.completion.sh
- etc/man/man1/meroxa-resources-create.1
- etc/man/man1/meroxa-resources-rotate-tunnel-key.1
- etc/man/man1/meroxa-resources-update.1
- etc/man/man1/meroxa-resources-validate.1
- go.mod
- go.sum
- vendor/github.com/meroxa/meroxa-go/resource.go
- vendor/modules.txt
```
$ m resource validate tunnel
Resource "tunnel" validation is successfully triggered!
Meroxa will try to connect to the resource for 60 minutes and send an email confirmation after a successful resource validation.
$ m resource rotate-tunnel-key tunnel
Rotating tunnel key will restart the tunnel and disconnect existing connections.
To proceed, type "tunnel" or re-run this command with --force
▸ tunnel
Resource "tunnel" tunnel key is successfully rotated!
Paste the following public key on your host:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMmFyvz3uE/ieininL3510uYaw8+lfTFzevgX4ASSsJ7J0mP2L9ozuPAxA8pzqqc8sWfIo4uUPdDKYyH2lPM8kcvbZ1G43WQb0D8srcL3FWWWRka0/2nOADnGVqlbq4DHPW4KbyURvQw7bVXqrNQ9un/TvSEM8yMTJirxVochfqgQUO2MVlVYFVMBJyfIWWjanQ570QiiPOzVjCQn4y1UWx3Gy6mOTwAqw0nbGsEJIm65dy/SRXhqx+7R+3y1rP …
```
> Add resource actions commands

- cmd/meroxa/global/client.go
- cmd/meroxa/global/metrics.go
This pull-request is to accommodate the necessary changes for https://github.com/meroxa/platform-api/issues/432.
> Integrating CLI metrics with Meroxa API

- .github/workflows/pull_request.yml
Update acceptance tests to use MySQL
Fixes https://meroxa.atlassian.net/browse/PLATFORM-684
You can do that by opening a pull-request to our (🔒 private, for now) repository: https://github.com/meroxa/meroxa-docs.
✨ In the future, there will be a GitHub action taking care of these updates automatically. ✨
*Provide PR link:*
> Update acceptance tests workflow

- .github/workflows/pull_request.yml
Adds env vars for ssh tunnel test: https://github.com/meroxa/acceptance/pull/40
Fixes https://github.com/meroxa/acceptance/issues/31
You can do that by opening a pull-request to our (🔒 private, for now) repository: https://github.com/meroxa/meroxa-docs.
✨ In the future, there will be a GitHub action taking care of these updates automatically. ✨
*Provide PR link:*
> Add env vars for ssh tunnel acceptance test

- README.md
Just updating the README.md  :)
> Add link to Meroxa community in README.md

- cmd/meroxa/root/login/login.go
- cmd/meroxa/root/logout/logout.go
- cmd/meroxa/root/root.go
- cmd/meroxa/root/whoami/whoami.go
- docs/cmd/md/meroxa.md
- docs/cmd/md/meroxa_login.md
- docs/cmd/md/meroxa_logout.md
- docs/cmd/md/meroxa_whoami.md
- docs/cmd/www/meroxa-login.md
- docs/cmd/www/meroxa-logout.md
- docs/cmd/www/meroxa-whoami.md
- docs/cmd/www/meroxa.md
- etc/completion/meroxa.completion.sh
- etc/man/man1/meroxa-login.1
- etc/man/man1/meroxa-logout.1
- etc/man/man1/meroxa-whoami.1
- etc/man/man1/meroxa.1
Fixes https://github.com/meroxa/product/issues/93
Fixes https://github.com/meroxa/product/issues/94
```
❯ .m help
The Meroxa CLI allows quick and easy access to the Meroxa Data Platform.
Using the CLI you are able to create and manage sophisticated data pipelines
with only a few simple commands. You can get started by listing the supported
resource types:
meroxa resources list --types
Usage:
meroxa [command]
api         Invoke Meroxa API
auth        Authentication commands for Meroxa
billing     Open your billing page in a web browser
completion  Generate completion script
connect     Connect two resources together
connectors  Manage connectors on Meroxa
endpoints   Manage endpoints on Meroxa
help        Help about any command
open …
```
> feat: Expose auth commands to root documenting them

- .github/workflows/pull_request.yml
Add sql server url to github actions workflow to fix broken acceptance tests
> Add sql server url to ga workflow

- README.md
Updates Meroxa logo so it looks better in dark mode.
Inspired by https://twitter.com/adamwathan/status/1438096197672132617.
🎩 @ogeyejammy for creating it !
> feat: Update logo

- Makefile
- cmd/meroxa/root/environments/describe.go
- cmd/meroxa/root/environments/describe_test.go
- cmd/meroxa/root/environments/environments.go
- cmd/meroxa/root/environments/remove.go
- cmd/meroxa/root/environments/remove_test.go
- cmd/meroxa/root/environments/update.go
- cmd/meroxa/root/environments/update_test.go
- go.mod
- go.sum
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/environment.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/pipeline.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource.go
- vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
- vendor/modules.txt
Add a command that allows the name or config of an environment to be updated
Fixes https://github.com/meroxa/cli/issues/204
$ m env --help
Manage environments on Meroxa
Usage:
meroxa environments [command]
Aliases:
environments, env, environment
create      Create an environment
describe    Describe environment
list        List environments
remove      Remove environment
Flags:
-h, --help   help for environments
Global Flags:
--cli-config-file string   meroxa configuration file
--debug                    display any debugging information
--json                     output json
--timeout duration         set the duration of the client timeout in seconds (default 10s)
Use "meroxa environments [command] --help" for more information about a …
> Add environment update command

- cmd/meroxa/root/apps/init.go
- cmd/meroxa/root/apps/init_test.go
- go.mod
- go.sum
- vendor/modules.txt
Shells out and initializes the repository when running `meroxa apps init`
Fixes https://github.com/meroxa/turbine-project/issues/39
> initialize repository on apps init

- cmd/meroxa/root/apps/apps.go
- cmd/meroxa/root/apps/remove.go
- cmd/meroxa/root/apps/remove_test.go
- go.mod
- go.sum
- utils/tests.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/application.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/log.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
- vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
- vendor/github.com/meroxa/turbine/init/template/app.json
- vendor/modules.txt
Access to deleting an application 
Fixes https://github.com/meroxa/turbine-project/issues/44
> feat(apps): Command for application remove

- cmd/meroxa/root/apps/run.go
Fixes https://github.com/meroxa/turbine-project/issues/68
> bug(apps): use absolute path for run command

- cmd/meroxa/turbine_cli/utils.go
previously only logging on pipeline create, not on pipeline found
Fixes https://github.com/meroxa/turbine-project/issues/98
|||
> bug(turbine): Adjust to new pipeline log

- utils/display.go
- utils/display_test.go
Fixes https://github.com/meroxa/turbine-project/issues/144
> Formatter is unhelpful and makes things difficult to copy & paste

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/turbine_cli/golang/deploy.go
- cmd/meroxa/turbine_cli/javascript/deploy.go
- cmd/meroxa/turbine_cli/local_deployment.go
- cmd/meroxa/turbine_cli/utils.go
- log/spinner.go
In some environments we were showing the wrong character on failed deployments. This pull-request fixes it and adds color.
> fix: character on failed deployments (and add colors)

- cmd/meroxa/root/apps/init.go
- cmd/meroxa/root/apps/init_test.go
Fixes https://github.com/meroxa/platform-api/issues/1021
> Allow underscores in application names

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/init.go
- cmd/meroxa/root/apps/run.go
Fixes https://github.com/meroxa/turbine-project/issues/160
> help text not formatted well

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/deploy_test.go
- cmd/meroxa/root/apps/describe_test.go
- cmd/meroxa/root/apps/list_test.go
- cmd/meroxa/root/apps/remove.go
- cmd/meroxa/root/apps/remove_test.go
- go.mod
- go.sum
- utils/tests.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/application.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/connector.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
- vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
- vendor/modules.txt
Fixes https://github.com/meroxa/turbine-project/issues/138
Depends on https://github.com/meroxa/meroxa-go/pull/109
See Slack
> feat: apps remove tear down app completely + apps deploy tears down resources when failed

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/init.go
- cmd/meroxa/turbine_cli/python/deploy.go
- cmd/meroxa/turbine_cli/python/run.go
- go.mod
- go.sum
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/application.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/connector.go
- vendor/modules.txt
Fixes https://github.com/meroxa/turbine-project/issues/137
> Python deploy

- docs/cmd/md/meroxa_apps_deploy.md
- docs/cmd/md/meroxa_apps_init.md
- docs/cmd/md/meroxa_apps_run.md
- docs/cmd/www/meroxa-apps-deploy.md
- docs/cmd/www/meroxa-apps-init.md
- docs/cmd/www/meroxa-apps-run.md
- etc/man/man1/meroxa-apps-deploy.1
- etc/man/man1/meroxa-apps-init.1
- etc/man/man1/meroxa-apps-run.1
Updates CLI to pick up: https://github.com/meroxa/turbine-go/pull/29
> Updates to Go base apps

- cmd/meroxa/root/builds/builds.go
- docs/cmd/md/meroxa.md
- docs/cmd/md/meroxa_builds.md
- docs/cmd/md/meroxa_builds_describe.md
- docs/cmd/md/meroxa_builds_logs.md
- docs/cmd/www/meroxa-builds-describe.md
- docs/cmd/www/meroxa-builds-logs.md
- docs/cmd/www/meroxa-builds.md
- docs/cmd/www/meroxa.md
- etc/completion/meroxa.completion.sh
- etc/man/man1/meroxa-builds-describe.1
- etc/man/man1/meroxa-builds-logs.1
- etc/man/man1/meroxa-builds.1
- etc/man/man1/meroxa.1
Fixes https://github.com/meroxa/turbine-project/issues/176
**Before**
```
❯ .m help | grep build
```
**Now**
```
❯ .m help | grep builds
builds       Inspect Process Builds on Meroxa
```
❯ .m help build
Inspect Process Builds on Meroxa
Usage:
meroxa builds [command]
Aliases:
builds, build
describe    Describe a Meroxa Process Build
logs        List a Meroxa Process Build's Logs
```
https://github.com/meroxa/meroxa-docs/pull/91
> chore: document meroxa build commands

- cmd/meroxa/root/apps/deploy.go
- utils/display.go
Fixes https://github.com/meroxa/turbine-project/issues/169
|||
> Also remove binary when removing Dockerfile

- cmd/meroxa/turbine_cli/golang/build.go
- cmd/meroxa/turbine_cli/local_deployment.go
- go.mod
- go.sum
- vendor/github.com/meroxa/turbine-go/deploy/template/Dockerfile
- vendor/github.com/meroxa/turbine-go/init/template/app.go
- vendor/modules.txt
Fixes https://github.com/meroxa/turbine-project/issues/171
> Dockerfile and binary changes to accommodate vendor or no vendor

- cmd/meroxa/root/apps/deploy.go
> Remove commands don't like asterisks

- Makefile
- README.md
- cmd/meroxa/root/apps/deploy.go
- go.mod
- go.sum
- vendor/modules.txt
Clean up some comments and update references to private repositories.
> chore: clean up

- cmd/meroxa/root/apps/deploy.go
Followup to https://github.com/meroxa/platform-ui-v1/issues/372
|![dashboardurlbefore](https://user-images.githubusercontent.com/8811742/164193330-16658dee-57a1-40a6-8897-0c25eae2b89a.gif)|![dashboardurlafter](https://user-images.githubusercontent.com/8811742/164192879-9a1ea6ec-65c2-46c7-a6ac-694eee75d457.gif)|
> fix(apps:deploy): update dashboard url for app detail views

- cmd/meroxa/turbine_cli/javascript/build.go
- cmd/meroxa/turbine_cli/javascript/deploy.go
- cmd/meroxa/turbine_cli/javascript/init.go
Bumps turbine to latest here https://www.npmjs.com/package/@meroxa/turbine-js
> Bump turbine-js

- go.mod
- go.sum
- vendor/modules.txt
Fixes https://github.com/meroxa/turbine-project/issues/194
|||
> Updating to the latest

- cmd/meroxa/turbine_cli/utils.go
Fix output when download dependencies.
> fix: output when there are dependencies

- cmd/meroxa/turbine_cli/javascript/build.go
- cmd/meroxa/turbine_cli/javascript/deploy.go
- cmd/meroxa/turbine_cli/javascript/init.go
Updates to latest version of turbine-js that includes a new feature (connector config) and a couple of bugfixes 
https://github.com/meroxa/turbine-js/releases/tag/v0.1.7
> Update to turbine-js@0.1.7

- go.mod
- go.sum
- vendor/modules.txt
> chore: upgrade turbine-go

- .github/workflows/nightly-build.yml
- .github/workflows/release.yml
Fixes https://github.com/meroxa/turbine-project/issues/192
> feat: Create nightly build

- go.mod
- go.sum
- vendor/github.com/meroxa/turbine-go/deploy/deploy.go
- vendor/github.com/meroxa/turbine-go/function.go
- vendor/github.com/meroxa/turbine-go/init/template/app.go
- vendor/github.com/meroxa/turbine-go/interface.go
- vendor/modules.txt
The following commands were run to generate changes:  and
> chore: Upgrade to latest turbine-go

- cmd/meroxa/turbine_cli/utils.go
Bumps turbine-js to https://github.com/meroxa/turbine-js/releases/tag/v0.2.1
Fixes
+ MySQL -> fn -> PG setups
Adds
+ `unwrap` transform to turbine-js fns
+ `get` / `set` data accessors for fn records
See https://github.com/meroxa/turbine-js#function-api for more info
Before:
```js
anonymize(records) {
records.forEach((record) => {
let payload = record.value.payload;
if (
isAttributePresent(payload.after) &&
isAttributePresent(payload.after.customer_email)
) {
payload.after.customer_email = iAmHelping(
stringHash(payload.after.customer_email)
);
}
});
return records;
}
```
After:
```js
anonymize(records) {
records.forEach((record) => {
record.set(
"customer_email",
iAmHelping(stringHash(record.get("customer_email")))
);
});
// Used for most destinations
records.unwrap();
return records;
} …
```
> Update turbine-js to v0.2.1

- cmd/meroxa/turbine_cli/utils.go
Updates turbine-js to published version 0.3.1 
https://www.npmjs.com/package/@meroxa/turbine-js
Please note that turbine-js 0.3+ has the updated application creation flow.
> Update to turbine-js 0.3.1

- cmd/meroxa/root/config/set.go
- docs/cmd/md/meroxa_config_set.md
- docs/cmd/www/meroxa-config-set.md
- etc/man/man1/meroxa-config-set.1
Address formatting change suggested by @jkayh in https://github.com/meroxa/meroxa-docs/pull/135#discussion_r937038997.
https://github.com/meroxa/meroxa-docs/pull/135
> chore: fix formatting

- cmd/meroxa/turbine_cli/golang/deploy.go
This provides backward compatibility between CLI and the turbine-go new resource expanded format.
Reported by @ericcheatham 
Fixes https://github.com/meroxa/turbine-go/pull/80
|||
> Attempt to parse using expanded resource format, fall back to legacy text

- cmd/meroxa/root/apps/deploy.go
Regardless of the success or failure to upload to API, remove the artifacts. 
Fixes https://github.com/meroxa/turbine-project/issues/268
AFTER
> Remove tar.gz artifact regardless of error

- cmd/meroxa/turbine_cli/utils.go
> Clarity about GOPATH in spinner logs

- cmd/meroxa/turbine_cli/utils.go
Updating Turbine-JS version to latest one 
Fixes https://github.com/meroxa/turbine-js/pull/127
> Bump Turbine-JS Version to 0.5.0

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/turbine_cli/javascript/deploy.go
- cmd/meroxa/turbine_cli/python/deploy.go
Fixes changes overwritten from https://github.com/meroxa/cli/commit/c0d25aa829cd392874633368948ac1c03df06177
Changes were overwritten by 
https://github.com/meroxa/cli/pull/405/files
https://github.com/meroxa/cli/pull/410/files
> Return Specversion Arg

- .gitignore
- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/deploy_test.go
- cmd/meroxa/turbine_cli/golang/deploy.go
- cmd/meroxa/turbine_cli/javascript/deploy.go
- cmd/meroxa/turbine_cli/local_deployment.go
- cmd/meroxa/turbine_cli/python/deploy.go
- cmd/meroxa/turbine_cli/utils.go
> Enable feature branches for turbine

- cmd/meroxa/root/apps/deploy.go
Include app name to go dockerfile generation 
Before: Erroring on feature branch builds
```
#8 [4/4] COPY usergo.cross usergo
#8 ERROR: failed to calculate checksum of ref xlsvqils3jvgev7vea4n7dv2d::rbl7x87f6y9vnko97tfg62ej1: "/usergo.cross": not found
------
> [4/4] COPY usergo.cross usergo:
------
Dockerfile:5
--------------------
3 |     WORKDIR /app
4 |     COPY app.json /app
5 | >>> COPY usergo.cross usergo
6 |     ENTRYPOINT ["/app/usergo", "--serve"]
--------------------
error: failed to solve: failed to compute cache key: failed to calculate checksum of ref xlsvqils3jvgev7vea4n7dv2d::rbl7x87f6y9vnko97tfg62ej1: "/usergo.cross": not found
```
After: successful deploy
```
➜  test-go git:(feature-branch) meroxa apps deploy 
✔ Checked your language is …
```
> Include app name to go dockerfile gen

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/deploy_test.go
- docs/cmd/md/meroxa_apps_deploy.md
- docs/cmd/www/meroxa-apps-deploy.md
- etc/man/man1/meroxa-apps-deploy.1
Allow for app deploys when skip flag provided for non unique destination collections
Fixes https://github.com/meroxa/product/issues/510
> Deploy app when skip flag provided for non unique destination collections

- Makefile
- cmd/meroxa/root/apps/run.go
- cmd/meroxa/root/apps/run_test.go
- cmd/meroxa/root/apps/upgrade.go
- cmd/meroxa/root/apps/upgrade_test.go
- cmd/meroxa/turbine/golang/cli.go
- cmd/meroxa/turbine/golang/run.go
- cmd/meroxa/turbine/golang/upgrade.go
- cmd/meroxa/turbine/interface.go
- cmd/meroxa/turbine/javascript/cli.go
- cmd/meroxa/turbine/javascript/run.go
- cmd/meroxa/turbine/javascript/upgrade.go
- cmd/meroxa/turbine/mock/cli.go
- cmd/meroxa/turbine/python/cli.go
- cmd/meroxa/turbine/python/run.go
- cmd/meroxa/turbine/python/upgrade.go
Expanding TurbineCLI interface to include the Run command
adjust Upgrade accordingly
Related to https://github.com/meroxa/turbine-project/issues/251
|||
> Refine interface and use interface in the apps run command

- cmd/meroxa/root/resources/create.go
- docs/cmd/md/meroxa_resources_create.md
- docs/cmd/www/meroxa-resources-create.md
- etc/man/man1/meroxa-resources-create.1
I realized that for `resources create` we were missing some more complicated examples. This pull-request fixes that.
**Before**
```bash
Use the create command to add resources to your Meroxa resource catalog.
Usage:
meroxa resources create [NAME] --type TYPE --url URL [flags]
Aliases:
create, add
Examples:
meroxa resources create store --type postgres -u $DATABASE_URL --metadata '{"logical_replication":"true"}'
meroxa resources create datalake --type s3 -u "s3://$AWS_ACCESS_KEY_ID:$AWS_ACCESS_KEY_SECRET@us-east-1/meroxa-demos"
meroxa resources create warehouse --type redshift -u $REDSHIFT_URL
meroxa resources create slack --type url -u $WEBHOOK_URL
```
**After**
```bash
Usage:
meroxa resources create [NAME] --type TYPE --url URL [flags]
Aliases:
create, add
Examples:
$ meroxa resources …
```
> doc: update resource create examples

- cmd/meroxa/turbine/golang/run.go
Fixes https://github.com/meroxa/cli/issues/428
BEFORE
AFTER
> Error output from go run missing

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/deploy_test.go
- cmd/meroxa/turbine/utils.go
Prepare feature branch deploy for release
Fixes  https://github.com/meroxa/product/issues/422
|||
> Prepare feature branch deploy for release

- cmd/meroxa/root/apps/describe_test.go
- cmd/meroxa/root/resources/create.go
- go.mod
- go.sum
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/api_errors.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/auth.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/environment.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource_types.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/transform.go
- vendor/modules.txt
Adds example of using confluent cloud
> Add Confluent Cloud to CLI

- .github/dependabot.yml
- .github/workflows/dependabot-auto-merge-go.yml
Copied from Conduit, cuz they are ahead of the curve. Dependabot should open PRs as new versions are found weekly.
Related to https://github.com/meroxa/engineering/issues/24
|||
> Add dependabot config to automatically update dependencies

- cmd/meroxa/root/account/accounts.go
- cmd/meroxa/root/account/list.go
- cmd/meroxa/root/account/list_test.go
- cmd/meroxa/root/root.go
- docs/cmd/md/meroxa.md
- docs/cmd/md/meroxa_account.md
- docs/cmd/md/meroxa_account_list.md
- docs/cmd/www/meroxa-account-list.md
- docs/cmd/www/meroxa-account.md
- docs/cmd/www/meroxa.md
- etc/completion/meroxa.completion.sh
- etc/man/man1/meroxa-account-list.1
- etc/man/man1/meroxa-account.1
- etc/man/man1/meroxa.1
- go.mod
- go.sum
- utils/display/accounts.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/account.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/auth.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/log.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/options.go
- vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
- vendor/modules.txt
It gives the user the possibility to list accounts attached to the user.
Fixes #393
> List Accounts

- cmd/meroxa/global/client.go
- cmd/meroxa/global/global.go
- cmd/meroxa/root/account/accounts.go
- cmd/meroxa/root/account/list.go
- cmd/meroxa/root/account/list_test.go
- cmd/meroxa/root/account/set.go
- cmd/meroxa/root/account/set_test.go
- docs/cmd/md/meroxa_account_set.md
- docs/cmd/www/meroxa-account-set.md
- docs/cmd/www/meroxa-account.md
- etc/completion/meroxa.completion.sh
- etc/man/man1/meroxa-account-set.1
- utils/display/accounts.go
Set user's account use.
Fixes #394
> Set Account

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/deploy_test.go
- go.mod
- go.sum
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/account.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/application.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/build.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/connector.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/deployment.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/endpoint.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/environment.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/function.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/log.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/pipeline.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource_types.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/source.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/transform.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/user.go
- vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
- vendor/modules.txt
GetLatest is not deterministic enough, so use the GetByUUID endpoint for fetching a new deployment
Fixes https://github.com/meroxa/product/issues/571
|||
> [IR] Use get by uuid instead of get latest for in waitForDeployment

- cmd/meroxa/turbine/utils.go
Updates to latest turbine-js
Fixes issue where output was "stringified in name only" 😂 
|||
> fix(turbine-js): bump to 1.3.1

- cmd/meroxa/turbine/python/upgrade.go
> Bump turbine-py version to latest release

- cmd/meroxa/turbine/utils.go
Bumps to 1.3.2 to include spec formatting fix
|||
> Bump to turbine-js 1.3.2

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/deploy_test.go
Fixes https://github.com/meroxa/product/issues/582
**Before (either failed or succeeded)**
```
...
✔ Successfully built process image ("d7a8b206-8433-4da4-abe2-af108a33910e")
Deploying application "filter-app"...
successfully validated application pipeline
successfully created source connector
successfully created function
successfully created destination connector on "pg"/"test_out"
successfully created all destination connectors
✔ Application "filter-app" successfully created!
```
**After (when it succeeded)**
```
...
✔ Successfully built process image ("d7a8b206-8433-4da4-abe2-af108a33910e")
Deploying application "filter-app"...
✔ Application "filter-app" successfully created!
```
**After (when it failed)**
```
...
✔ Successfully built process image …
```
> feat: show deployment logs when it fails

- cmd/meroxa/turbine/utils.go
> bug: Nil pointer in upload

- utils/display/apps.go
- utils/display/apps_test.go
Fixes https://github.com/meroxa/product/issues/596
**Before**
```
anonymize-d50ba9ef (function)
[2022-10-26T12:31:47Z] gRPC server started at 0.0.0.0:8081
[2022-10-26T12:33:31Z] gRPC server started at 0.0.0.0:8081
49239dd8-fe6e-4f4d-a3d1-0c5ac3b76686 (deployment)
successfully validated application pipeline
successfully created source connector
successfully created function
successfully created destination connector to resource "demopg" with collection "user_activity_js_ir"
successfully created all destination connectors
```
**After**
```
[2022-10-26T12:31:47Z] gRPC server started at 0.0.0.0:8081
[2022-10-26T12:33:31Z] gRPC server started at 0.0.0.0:8081
successfully validated application pipeline
successfully created source connector
successfully created function
successfully created …
```
> feat: improve output logs

- cmd/meroxa/root/apps/logs.go
- cmd/meroxa/root/apps/logs_test.go
- go.mod
- go.sum
- utils/display/apps.go
- utils/display/apps_test.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/application.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
- vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
- vendor/modules.txt
One request for all the app logs
Fixes https://github.com/meroxa/turbine-project/issues/280
|||
> App logs from one request

- cmd/meroxa/turbine/utils.go
Latest turbine-js-cli with version bug fix
|||
> Bump turbine-js-cli version to 1.3.4

- cmd/meroxa/turbine/utils.go
> Use the latest turbine-js-cli@1.3.5

- cmd/meroxa/root/resources/list.go
Fixes https://github.com/meroxa/cli/issues/541
|
|
|
> Provide a link to the dashboard from the resources list command

- cmd/meroxa/root/apps/apps.go
- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/deploy_test.go
- cmd/meroxa/root/resources/create.go
- cmd/meroxa/turbine/golang/build.go
- cmd/meroxa/turbine/golang/deploy.go
- cmd/meroxa/turbine/golang/run.go
- cmd/meroxa/turbine/interface.go
- cmd/meroxa/turbine/javascript/build.go
- cmd/meroxa/turbine/javascript/cli.go
- cmd/meroxa/turbine/javascript/cli_test.go
- cmd/meroxa/turbine/javascript/deploy.go
- cmd/meroxa/turbine/javascript/init.go
- cmd/meroxa/turbine/javascript/run.go
- cmd/meroxa/turbine/javascript/version.go
- cmd/meroxa/turbine/mock/cli.go
- cmd/meroxa/turbine/python/build.go
- cmd/meroxa/turbine/python/cli.go
- cmd/meroxa/turbine/python/deploy.go
- cmd/meroxa/turbine/ruby/build.go
- cmd/meroxa/turbine/ruby/deploy.go
- cmd/meroxa/turbine/ruby/internal/cmd.go
- cmd/meroxa/turbine/ruby/internal/cmd_test.go
- cmd/meroxa/turbine/ruby/run.go
- cmd/meroxa/turbine/utils.go
- cmd/meroxa/turbine/utils_test.go
- go.mod
- vendor/modules.txt
Deploy ruby app with function
Fixes https://github.com/meroxa/cli/issues/523
- collection `sequences`
adds 100 to `id` column
```
class Passthrough < TurbineRb::Process
def call(records:)
require 'json'
puts "got records: #{records}"
records.map do |r|
value = JSON.parse(r.value)
value["payload"]["id"] = value["payload"]["id"] + 100
Io::Meroxa::Funtime::Record.new(key: r.key, value: value.to_json, timestamp: r.timestamp)
end
end
end
```
- collection: `diana_tests_functions5`
> Deploy ruby function

- .github/workflows/ci.yml
- cmd/meroxa/root/apps/deploy.go
Fixes https://github.com/meroxa/product/issues/622
|||
> Use custom CLI binary into the acceptance container

- cmd/meroxa/root/resources/create.go
- cmd/meroxa/root/resources/create_test.go
- go.mod
- go.sum
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/function.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource_types.go
- vendor/modules.txt
Notion resource and connector for Mantium
Related to https://github.com/meroxa/platform-api/issues/1552
|||
> Notion resource and pulling in conduit Notion connector

- go.mod
- go.sum
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource.go
- vendor/modules.txt
> Meroxa-go should not require a URL

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/deploy_test.go
> Bring back the teardown prep for deployment

- utils/display/resources.go
Fixes https://github.com/meroxa/cli/issues/579
|
|
|
> Do not print empty fields in the describe context

- go.mod
- go.sum
- vendor/google.golang.org/grpc/balancer/grpclb/state/state.go
- vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
- vendor/google.golang.org/grpc/version.go
- vendor/modules.txt
> Inconsistent vendor

- cmd/meroxa/root/resources/create.go
- go.mod
- go.sum
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/application.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource_types.go
- vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
- vendor/modules.txt
> Update meroxa-go vendor

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/deploy_test.go
> Fix typo on functions support for env

- cmd/meroxa/root/apps/list_test.go
- go.mod
- go.sum
- utils/display/apps.go
- utils/display/apps_test.go
- utils/tests.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/application.go
- vendor/modules.txt
We are no longer pulling type and provider info for Envs on Apps. Making changes according to that. 
Fixes <https://github.com/meroxa/cli/issues/622>
> Env app describe and ls changes 

- cmd/meroxa/root/resources/list.go
The final CLI change before cutting the release for connector roadmap phase 1. 
Fixes https://github.com/meroxa/cli/issues/597
|||
> [ Do not merge] Add URL to dashboard resource catalog

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/deploy_test.go
- go.mod
- go.sum
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/application.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/build.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/deployment.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource_types.go
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/source.go
- vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
- vendor/modules.txt
Fixes https://github.com/meroxa/cli/issues/635
Fixes https://github.com/meroxa/cli/issues/637
This will be ready to ship once the following are done:
Assuming application contains a function.
**Before**
```
$ meroxa apps deploy --env my-env
Error: cannot deploy an application with a function to an environment
```
**After**
```
$ meroxa apps deploy --env my-env
...
```
⚠️ Blocked on https://github.com/meroxa/platform-api/issues/1694
> feat(deploy):  Enables apps deployments with functions to environments

- .goreleaser.yml
Adding goreleaser updates for Scoop manifest 
Fixes <https://github.com/meroxa/cli/issues/474>
> Update goreleaser for Scoop

- cmd/meroxa/turbine/utils.go
- cmd/meroxa/turbine/utils_test.go
Finish enhancing unit test coverage by testing the Turbine utils file
Fixes https://github.com/meroxa/turbine-project/issues/284
|||
> Unit test coverage for Turbine utils

- cmd/meroxa/root/apps/deploy_test.go
- cmd/meroxa/root/apps/list_test.go
- cmd/meroxa/root/apps/run_test.go
- cmd/meroxa/turbine/ruby/deploy_test.go
- cmd/meroxa/turbine/ruby/run_test.go
Proper use of gomock
Related to https://github.com/meroxa/product/issues/715
|||
> Proper use of gomock Finish and NewController

- cmd/meroxa/root/apps/deploy.go
Something we forgot doing on https://github.com/meroxa/cli/pull/666.
> fix: unused method

- cmd/meroxa/root/resources/create.go
- cmd/meroxa/root/resources/update.go
- cmd/meroxa/root/resources/update_test.go
> Also ignore URL for Notion and Spire in resource update

- cmd/meroxa/root/apps/deploy.go
- cmd/meroxa/root/apps/deploy_test.go
- cmd/meroxa/turbine/golang/utils.go
- cmd/meroxa/turbine/javascript/cli.go
- cmd/meroxa/turbine/javascript/deploy.go
- cmd/meroxa/turbine/javascript/internal/cmd.go
- cmd/meroxa/turbine/javascript/run.go
- go.mod
- go.sum
- vendor/github.com/meroxa/turbine-core/pkg/app/templates/javascript/package.json
- vendor/github.com/meroxa/turbine-core/pkg/app/templates/python/main.py
- vendor/github.com/meroxa/turbine-core/pkg/app/templates/python/requirements.txt
- vendor/modules.txt
Closes https://github.com/meroxa/cli/issues/690
Closes https://github.com/meroxa/cli/issues/691
+ `meroxa apps deploy` 
+ `meroxa apps run` 
...for turbine-js apps using >= `turbine-js@2.0.0-alpha.6`
> feat(turbine): turbine-core js deploy & run

- cmd/meroxa/turbine/internal/port.go
- cmd/meroxa/turbine/javascript/deploy.go
Fixes turbine javascript deploy to use the correct randomized port
> fix(turbine-js): correct runAddr random port

- cmd/meroxa/turbine/python/version.go
- cmd/meroxa/turbine/utils.go
- cmd/meroxa/turbine/utils_test.go
> removing windows partial new line token from the version

- go.mod
- go.sum
- vendor/github.com/meroxa/turbine-core/pkg/app/init.go
- vendor/modules.txt
Updates to get https://github.com/meroxa/turbine-core/pull/130
> fix: upgrade to latest turbine-core for py win fix

- cmd/meroxa/root/apps/init.go
- cmd/meroxa/turbine/javascript/internal/cmd.go
- cmd/meroxa/turbine/javascript/upgrade.go
- cmd/meroxa/turbine/javascript/version.go
Fixes https://github.com/meroxa/turbine-js/issues/305
Also cleans up upgrade/version commands in JS to rely on the newest version of turbine-js
> fix: init path on windows

- go.mod
- go.sum
- vendor/github.com/meroxa/turbine-core/pkg/app/init.go
- vendor/github.com/meroxa/turbine-core/pkg/app/templates/golang/.gitignore
- vendor/github.com/meroxa/turbine-core/pkg/app/templates/javascript/.gitignore
- vendor/github.com/meroxa/turbine-core/pkg/app/templates/python/.gitignore
- vendor/github.com/meroxa/turbine-core/pkg/app/templates/python/__init__.py
- vendor/github.com/meroxa/turbine-core/pkg/app/templates/python/main.py
- vendor/github.com/meroxa/turbine-core/pkg/app/templates/python/requirements.txt
- vendor/github.com/stretchr/testify/assert/assertion_compare.go
- vendor/github.com/stretchr/testify/assert/assertion_format.go
- vendor/github.com/stretchr/testify/assert/assertion_forward.go
- vendor/github.com/stretchr/testify/assert/assertion_order.go
- vendor/github.com/stretchr/testify/assert/assertions.go
- vendor/github.com/stretchr/testify/assert/doc.go
- vendor/github.com/stretchr/testify/assert/http_assertions.go
- vendor/github.com/stretchr/testify/require/doc.go
- vendor/github.com/stretchr/testify/require/require.go
- vendor/github.com/stretchr/testify/require/require_forward.go
- vendor/modules.txt
Pulls in latest turbine-core with fix for app initialization dotfiles
> build(deps): upgrade turbine-core

- cmd/meroxa/turbine/golang/init.go
Fixes https://github.com/meroxa/cli/issues/746
> fix: windows GOPATH detection

- cmd/meroxa/root/apps/describe_test.go
- cmd/meroxa/root/apps/init_test.go
- cmd/meroxa/root/apps/logs_test.go
- cmd/meroxa/root/apps/open_test.go
- cmd/meroxa/root/apps/remove_test.go
- cmd/meroxa/root/resources/create_test.go
- cmd/meroxa/turbine/utils_test.go
Update unit tests, as well, to be able to run them on any OS
Related to https://github.com/meroxa/product/issues/815
|||
> Form file paths in an OS agnostic way

- cmd/meroxa/turbine/golang/deploy.go
- cmd/meroxa/turbine/golang/run.go
- cmd/meroxa/turbine/javascript/deploy.go
- cmd/meroxa/turbine/javascript/run.go
- cmd/meroxa/turbine/python/deploy.go
- cmd/meroxa/turbine/python/run.go
- cmd/meroxa/turbine/ruby/deploy.go
- cmd/meroxa/turbine/ruby/run.go
> Revert "Exit 1 when grpc requests fail"

- .gitignore
- cmd/meroxa/turbine/golang/init.go
> Update link for guidance about initializing a Go app

- .golangci.yml
- cmd/meroxa/flink/deploy.go
- cmd/meroxa/flink/init.go
- cmd/meroxa/root/environments/create.go
- cmd/meroxa/root/environments/create_test.go
- cmd/meroxa/root/environments/update.go
- cmd/meroxa/root/environments/update_test.go
- cmd/meroxa/root/flink/deploy.go
- utils/slice_to_map.go
Working with Flink Java to get an IR spec
Fixes https://github.com/meroxa/product/issues/854
|||
> Extract Connector IR from JAR

- cmd/meroxa/flink/deploy.go
- cmd/meroxa/root/flink/deploy.go
- cmd/meroxa/root/flink/deploy_test.go
- go.mod
- go.sum
- vendor/github.com/meroxa/meroxa-go/pkg/meroxa/flink_job.go
- vendor/modules.txt
Temporary workflow to validate how Flink Jobs and connectors can work together
Fixes https://github.com/meroxa/product/issues/860
|||
> Send valid IR spec with Flink deploy request

- .github/workflows/nightly-build.yml
Updates nightly builds from daily to once a month.
> chore: update nightly builds to once a month

- cmd/meroxa/global/basic_client.go
**Before**
```
$(go env GOPATH)/bin/meroxa login
Error: please login or signup by running 'meroxa login'
```
**Now**
```
.m login
$(go env GOPATH)/bin/meroxa apps ls
SPECVERSION   CREATED   UPDATED   NAME   STATE
============= ========= ========= ====== =======
✨ To view your applications, visit https://dashboard.meroxa.io/apps
$(go env GOPATH)/bin/meroxa logout
Successfully logged out.
$(go env GOPATH)/bin/meroxa apps ls
Error: please login or signup by running 'meroxa login'
```
> fix: login

- cmd/meroxa/root/apps/apps.go
- cmd/meroxa/root/apps/describe.go
- cmd/meroxa/root/apps/describe_test.go
- cmd/meroxa/root/apps/list_test.go
- cmd/meroxa/root/apps/remove.go
Adding version and language headers to describe and remove requests 
Fixes https://github.com/meroxa/mdpx/issues/657
Headers can now be seen as part of requests 
Describe - 
Remove -
> Add version and language headers to describe and remove

- cmd/meroxa/root/secrets/secrets.go
Removing secrets update command on cli for the monarch project 
Fixes https://github.com/meroxa/mdpx/issues/1072
> Secrets upgrade

- .github/workflows/release.yml
- go.mod
Upgrade go to 1.22
See notes https://tip.golang.org/doc/go1.22#language
> feat: upgrade go 1.22
