.goreleaser.yml

Something I should have done in https://github.com/meroxa/cli/pull/87.
Currently, version is shown as `meroxa/0.2.2 darwin/amd64` which wouldn't make the assertion to pass. This PR makes sure that's the case.
**Before**
```
test do
shell_output("#{bin}/meroxa version").match(/v0.2.2/)
end
```
**Now**
```
...
test do
shell_output("#{bin}/meroxa version").match(/0.2.2/)
end
```

fix(cli) Make sure v is not included when testing

---

.github/workflows/release.yml

The secret used previously which I assumed would work to push to `meroxa/homebrew-taps` is not present in this repository. This PR updates it to the proper GitHub token.
This should fix an automated homebrew release to [`meroxa/homebrew-taps`](https://github.com/meroxa/homebrew-taps) which failed such as https://github.com/meroxa/cli/runs/2194410513?check_suite_focus=true.
See https://goreleaser.com/customization/homebrew/ for more information.

Update GH token

---

cmd/logs_connector.go
go.mod
go.sum
vendor/modules.txt

I would love to be able to pipe the output of our commands as input into others:
```
meroxa logs connector sfdb-122-902992 | pbcopy
```
This change updates the logs command for connectors to write to `Stdout` vs `Stderr`.

Write connector logs to stdout

---

go.mod
go.sum
vendor/github.com/meroxa/meroxa-go/resource.go
vendor/modules.txt

To bring https://github.com/meroxa/meroxa-go/pull/31 which fixes:
```
❯ .m add resource --type postgres -u "postgres://useroP24ThrN:HaRrXsOlTcXhscVd@meroxa-demo.cwyhi7jl0lln.us-east-2.rds.amazonaws.com:5432/dboP24ThrN" --json
{
"id": 472,
"type": "postgres",
"name": "",
"url": "postgres://meroxa-demo.cwyhi7jl0lln.us-east-2.rds.amazonaws.com:5432/dboP24ThrN"
}
❯ .m list resources
ID       NAME         TYPE                                           URL
===== ============= ========== =================================================================================
472                 postgres   postgres://meroxa-demo.cwyhi7jl0lln.us-east-2.rds.amazonaws.com:5432/dboP24ThrN
420   my-resource   postgres   postgres://meroxa-demo.cwyhi7jl0lln.us-east-2.rds.amazonaws.com:5432/dboP24ThrN
❯ .m …
```

chore(cli): Update meroxa-go

---

cmd/root.go

Platform-api master is currently failing on `context deadline exceeded`. We need to bump up the `clientTimeOut` time to help unblock release process while we look into the performance issue. 
*Provide link:*

Bump context timeout to 10 seconds

---

cmd/add_resource.go
cmd/create_connector.go
cmd/create_connector_test.go
cmd/create_pipeline.go
cmd/update_pipeline.go
cmd/update_pipeline_test.go
cmd/update_resource.go
cmd/update_resource_test.go
docs/cmd/meroxa_add_resource.md
etc/man/man1/meroxa-add-resource.1
go.mod
go.sum
vendor/github.com/meroxa/meroxa-go/connector.go
vendor/github.com/meroxa/meroxa-go/pipeline.go
vendor/github.com/meroxa/meroxa-go/resource.go
vendor/modules.txt

Fixes https://meroxa.atlassian.net/browse/PLATFORM-439
The UI is sending certain attributes that are legitimate booleans, and both meroxa-go and CLI have been treating them as strings causing an unmarshal error such as:
`Error: json: cannot unmarshal bool into Go struct field Resource.metadata of type string`.
```
$ meroxa list resources
Error: json: cannot unmarshal bool into Go struct field Resource.metadata of type string
```
```
$ meroxa list resources
ID         NAME           TYPE                                           URL
===== ================= ========== =================================================================================
420   my-resource       postgres …
```

[PLATFORM-439] fix(cli): Let handle values as bool

---

README.md

This adds a short troubleshooting section to the Readme for users who run into errors when trying to download depdencies for manual builds of the CLI via ssh.
`make gomod`
```
GOPRIVATE=github.com/meroxa/meroxa-go go mod tidy && go mod vendor
go: github.com/meroxa/meroxa-go@v0.0.0-20210426150351-91d304d1dc66: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/jj/go/pkg/mod/cache/vcs/71a674a412aadf62e5b2139080161bcb281719f14a92bd858bb28986fb7c4171: exit status 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
make: *** [gomod] Error 1
```
Check out the new Readme [here](https://github.com/meroxa/cli/blob/57809dae793431ab74618c7e929283be39eb9891/README.md#troubleshooting)

docs: add troubleshooting section for SSH-based downloads using gomod

---

.github/pull_request_template.md
README.md

Updates our CLI repository with some broken links to the docs.
Fixes https://meroxa.atlassian.net/browse/PLATFORM-675

[PLATFORM-675] fix: reference to old docs

---

cmd/meroxa/builder/builder.go
cmd/meroxa/global/config.go
cmd/meroxa/global/global.go
cmd/meroxa/root/env/env.go
cmd/meroxa/root/env/env_test.go
cmd/meroxa/root/root.go

Occasionally, I wonder where my configuration lives or its content. This command  will help with that.
It's hidden for now, but it'll be available in case we ask customers to run it for us.
This pull-request also adds the option to build hidden commands via builder.
Fixes https://meroxa.atlassian.net/browse/PLATFORM-662
**nonexistent command**
```
❯ meroxa env
The Meroxa CLI allows quick and easy access to the Meroxa Data Platform.
Using the CLI you are able to create and manage sophisticated data pipelines
with only a few simple commands. You can get started by listing the supported
resource types:
meroxa resources list --types
Usage:
meroxa [command]
api         Invoke Meroxa API
auth        Authentication commands for Meroxa
billing …
```

[PLATFORM-662] feat: Add environment command

---

cmd/meroxa/root/resources/create.go
cmd/meroxa/root/resources/create_test.go
cmd/meroxa/root/resources/describe.go
cmd/meroxa/root/resources/describe_test.go
cmd/meroxa/root/resources/update.go
go.mod
go.sum
utils/display.go
vendor/github.com/meroxa/meroxa-go/api_errors.go
vendor/github.com/meroxa/meroxa-go/resource.go
vendor/modules.txt

Add tunnel creation, update, list, and describe. This depends on https://github.com/meroxa/meroxa-go/pull/40. The `meroxa resources describe` layout is changed to accommodate the ssh tunnel display.
Fixes https://meroxa.atlassian.net/browse/PLATFORM-594
Fixes https://meroxa.atlassian.net/browse/PLATFORM-595
Fixes https://meroxa.atlassian.net/browse/PLATFORM-596
```
$ m resources create tunnel --type postgres -u DB_URL --ssh-url SSH_TUNNEL_ADDR
$ m resources update tunnel --type postgres -u DB_URL --ssh-url SSH_TUNNEL_ADDR
$ m resource list
ID      NAME       TYPE                                              URL                                             SSH TUNNELED
====== ========== ========== ======================================================================================== …
```

[PLATFORM-594] [PLATFORM-595] [PLATFORM-741] Add SSH Tunnel commands

---

cmd/meroxa/global/metrics.go
cmd/meroxa/global/metrics_test.go

Uses the same one as in [API](https://github.com/meroxa/platform-api/blob/9590cb367ce10a82c9d609c4a07dff299b5e9980/cmd/api/config/config.go#L52) so it's consistent.

chore: Rename env name for metrics key

---

.github/workflows/pull_request.yml

staging acceptance tests are failing `Error: HTTP/2.0 401 Unauthorized` because cli uses production auth0 tenant while api uses staging tenant
Fixes https://github.com/meroxa/acceptance/issues/41
You can do that by opening a pull-request to our (🔒 private, for now) repository: https://github.com/meroxa/meroxa-docs.
✨ In the future, there will be a GitHub action taking care of these updates automatically. ✨
*Provide PR link:*

Use auth0 secrets with environment context

---

cmd/meroxa/root/api/api.go

Allow output JSON only for `meroxa api`. Previously, it outputs the headers & JSON body, and can run into JSON parsing issues.
```
m api GET /v1/connectors
> GET /v1/connectors
< 200 OK HTTP/2.0
< Date Wed, 28 Jul 2021 19:47:35 GMT
< Content-Type application/json; charset=utf-8
< Content-Length 330
< Meroxa-Request-Id 76c95e19-3030-46f5-884b-8118810add42
< Vary Origin
[
{
"id": 580,
"name": "hello",
"type": "jdbc-source",
"config": {},
"state": "running",
"resource_id": 275,
"pipeline_id": 3,
"pipeline_name": "default",
"streams": {
"output": [
"resource-275-984998-tt"
],
"dynamic": false
},
"metadata": {
"mx:connectorType": "source"
},
"created_at": "2021-04-28T22:47:31.867391Z",
"updated_at": "2021-07-28T19:47:28.940729Z"
}
]
could not unmarshal: …
```

Allow output JSON only for `meroxa api`

---

cmd/meroxa/global/client.go
cmd/meroxa/global/config.go
cmd/meroxa/global/metrics_test.go
cmd/meroxa/root/auth/login.go

Currently CLI has auth config vars hardcoded. We want to change this to allow new values depending on environment
Fixes https://github.com/meroxa/product/issues/81

Use env vars for auth configs

---

cmd/meroxa/root/api/api.go
log/json.go

Reverts meroxa/cli#169
----
`--json` already worked and only showing the body content as expected however #169 did caught an issue with arrays, which is what this pull-request is addressing.
**before**
```
❯ .m api get /v1/connectors --json
could not unmarshal: %!w(*json.UnmarshalTypeError=&{array 0x1500580 1  })
Error: json: cannot unmarshal array into Go value of type map[string]interface {}
```
**now**
```
❯ .m api get /v1/connectors --json
[
{
"id": 583,
"name": "my-resource-149-954565",
"type": "jdbc-source",
"config": {},
"state": "failed",
"trace": "trace",
"resource_id": 149,
"pipeline_id": 11,
"pipeline_name": "default",
"streams": {
"output": [
"resource-149-942792-public.User"
],
"dynamic": false
},
"metadata": {
"mx:connectorType": "source"
},
"created_at": …
```

fix: Unmarshal error on meroxa api --json

---

.github/workflows/release.yml

As suggested by @terrancej yesterday's at stand up, a good practice would be to start signing our releases with our GPG key generated.
Both secrets were enabled to this repository as well.

feat: Sign commits with GPG

---

cmd/meroxa/root/connectors/create.go
cmd/meroxa/root/connectors/create_test.go
etc/completion/meroxa.completion.sh

For a JDBC connector, query and input are mutually exclusive. So to allow customers to set query config, we need to stop making input flag required 
Fixes https://github.com/meroxa/product/issues/87
You can do that by opening a pull-request to our (🔒 private, for now) repository: https://github.com/meroxa/meroxa-docs.
✨ In the future, there will be a GitHub action taking care of these updates automatically. ✨
*Provide PR link:*

Make connector input not a required field

---

cmd/meroxa/builder/builder.go
docs/cmd/md/meroxa_auth.md
docs/cmd/md/meroxa_connectors.md
docs/cmd/md/meroxa_endpoints.md
docs/cmd/md/meroxa_open.md
docs/cmd/md/meroxa_pipelines.md
docs/cmd/md/meroxa_resources.md
docs/cmd/md/meroxa_transforms.md
docs/cmd/www/meroxa-auth.md
docs/cmd/www/meroxa-connectors.md
docs/cmd/www/meroxa-endpoints.md
docs/cmd/www/meroxa-open.md
docs/cmd/www/meroxa-pipelines.md
docs/cmd/www/meroxa-resources.md
docs/cmd/www/meroxa-transforms.md

Fixes https://github.com/meroxa/cli/issues/162
Fixes https://github.com/meroxa/product/issues/63
```
❯ .m resources
```
```
❯ .m resources
Usage:
meroxa resources [flags]
meroxa resources [command]
Aliases:
resources, resource
create            Add a resource to your Meroxa resource catalog
describe          Describe resource
list              List resources and resource types
remove            Remove resource
rotate-tunnel-key Rotate the tunnel key for a resource
update            Update a resource
validate          Validate a resource
Flags:
-h, --help   help for resources
Global Flags:
--config string      config file
--debug              display any debugging information
--json               output json …
```

fix: Show help text on base commands

---

cmd/meroxa/builder/builder.go
cmd/meroxa/global/client.go
cmd/meroxa/global/global.go
cmd/meroxa/global/metrics.go
cmd/meroxa/global/metrics_test.go
cmd/meroxa/root/auth/login.go
cmd/meroxa/root/auth/logout.go
cmd/meroxa/root/auth/whoami.go
cmd/meroxa/root/auth/whoami_test.go
cmd/meroxa/root/environments/environments.go
cmd/meroxa/root/root.go
go.mod
go.sum
vendor/github.com/meroxa/meroxa-go/user.go
vendor/modules.txt

This pull-request adds the ability to create a CLI command that depends on a Meroxa User Feature Flag. These are returned by the API endpoint `/v1/users/me` and when that API endpoint is used in `meroxa whoami` we also make sure we update this information.
To make sure user information is not stale, we'll start fetching this information every 24hours since last time was updated.
To demo the usage of feature flags, this pull-request also adds the `environment` command which could aliased as `env` or `environment`.
Fixes https://github.com/meroxa/product/issues/113
~Depends on https://github.com/meroxa/meroxa-go/pull/53~.
- We didn't check for feature flags.
**Without feature flag enabled**
```bash
$ meroxa env
Error: feature flag "environments" required. reach out to support@meroxa.com for …
```

feat: Update user info every 24h and adds command with feature flag

---

cmd/meroxa/root/auth/logout.go

In the process of logging out, we should make sure we all reset user information in meroxa's configuration file. Otherwise, even when logging back in as a new user, information such as email, uuid and feature flags remained the same.
```
❯ meroxa config       
Using meroxa config located in "path"
...
access_token: old..token
actor: old@email.com
actor_uuid: old-uuid
refresh_token: old..token
user_feature_flags: my-feature-flag
...
❯ meroxa logout
Successfully logged out.
❯ meroxa config       
Using meroxa config located in "path"
...
access_token: 
actor: old@email.com
actor_uuid: old-uuid
refresh_token: 
user_feature_flags: my-feature-flag
...
❯ meroxa login 
You will now be taken to your browser for authentication or open the url below in a browser.
... …
```

fix: reset user info while logging out

---

cmd/meroxa/root/connectors/describe.go
cmd/meroxa/root/connectors/describe_test.go
utils/display.go
utils/display_test.go

A trace error is returned along with failed connectors. This PR displays the contents of the trace when the `connector describe` command is used.
Fixes https://github.com/meroxa/product/issues/186
```
➜  cli git:(ah/output-trace) ✗ meroxa connector describe cdbsrc
ID     NAME         TYPE                      STREAMS                 STATE    PIPELINE
====== ======== ================= ==================================== ======== ==========
2470   cdbsrc   cosmosdb-source   (output) resource-2957-203946-demo   failed   vercel
```
```
➜  cli git:(ah/output-trace) ✗ ./meroxa connector describe cdbsrc
ID:   2470
Name:   cdbsrc
Type:   cosmosdb-source
Streams:   (output) resource-2957-203946-demo
State:   failed
Pipeline:   Vercel
Trace: …
```

feat(connector): Include connector trace in `connector describe`

---

cmd/meroxa/root/connectors/update.go
cmd/meroxa/root/pipelines/update.go
docs/cmd/md/meroxa_connectors_update.md
docs/cmd/md/meroxa_pipelines_update.md
docs/cmd/www/meroxa-connectors-update.md
docs/cmd/www/meroxa-pipelines-update.md
etc/man/man1/meroxa-connectors-update.1
etc/man/man1/meroxa-pipelines-update.1

Working on https://meroxa.zendesk.com/agent/tickets/121 I realized we don't indicate well the different possible states when updating a pipeline. For `connectors update` we showed them as part of `usage` although it also included `[FLAGS]` right after it so it wasn't entirely right. This pull-request makes that a bit clearer.
```
Usage:
meroxa pipelines update NAME [flags]
Examples:
meroxa pipeline update old-name --name new-name
meroxa pipeline update pipeline-name --state pause
meroxa pipeline update pipeline-name --metadata '{"key":"value"}'
Flags:
...
--state string      new pipeline state
```
```
Usage:
meroxa pipelines update NAME [flags]
Examples:
meroxa pipeline update old-name --name new-name
meroxa pipeline update …
```

doc: Indicate possible states when updating a pipeline or a connector

---

.github/workflows/pull_request.yml
.github/workflows/release.yml

Updates CI actions that are part of the release workflow to the latest version. This should solve the problem with a deprecated setting in the generated brew formula (see https://github.com/meroxa/homebrew-taps/pull/1).
**This was not tested.** I went through the documentation of the CI actions and looks like the config did not change from what we had before.

Update CI actions in release workflow

---

cmd/meroxa/root/pipelines/create.go
cmd/meroxa/root/pipelines/create_test.go
cmd/meroxa/root/pipelines/describe.go
cmd/meroxa/root/pipelines/describe_test.go
cmd/meroxa/root/pipelines/pipelines.go
docs/cmd/md/meroxa_pipelines.md
docs/cmd/md/meroxa_pipelines_describe.md
docs/cmd/www/meroxa-pipelines-describe.md
docs/cmd/www/meroxa-pipelines.md
etc/completion/meroxa.completion.sh
etc/man/man1/meroxa-pipelines-describe.1
go.mod
go.sum
utils/display.go
utils/display_test.go
utils/tests.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/pipeline.go
vendor/modules.txt

- Fixes https://github.com/meroxa/cli/issues/211
- Fixes https://github.com/meroxa/cli/issues/212
- Fixes https://github.com/meroxa/cli/issues/213
Depends on https://github.com/meroxa/meroxa-go/pull/84
```
❯ meroxa pipelines ls                              
ID               NAME                STATE  
====== ============================= =========
762   meroxa-cli-to-slack/discord   healthy 
11             default             healthy 
1910            with-env             healthy
❯ .m pipelines describe default
Manage pipelines on Meroxa
Usage:
meroxa pipelines [command]
Aliases:
pipelines, pipeline
create      Create a pipeline
list        List pipelines
remove      Remove pipeline
update      Update pipeline name, state or metadata
...
❯ …
```

feat(pipelines): Add environments

---

.github/workflows/release.yml

Fix [latest release attempt to 1.5.0](https://github.com/meroxa/cli/runs/4353356352?check_suite_focus=true).
Looks like this was changed in [this changelog](https://github.com/crazy-max/ghaction-import-gpg/blob/cb4264d3319acaa2bea23d51ef67f80b4f775013/CHANGELOG.md#400-20210905), and we hadn't noticed it until we [bumped to latest `goreleaser` action (`v2`)](https://github.com/meroxa/cli/pull/218/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R32).

fix: go releaser

---

cmd/meroxa/root/environments/create.go

In the env create example, the --config string doesn't marshal to a map and the \ for newline get translated to returns
- [X ]  Documentation
- [ X]  Unit Tests
Usage:
meroxa environments create NAME [flags]
Examples:
meroxa env create my-env \
--type hosted \ 
--provider aws \ 
--region us-east-1 \ 
--config '{\"aws_access_key_id\":\"my_access_key\", \"aws_secret_access_key\":\"my_secret_access_key\"}'
Flags:
-c, --config string     environment configuration based on type and provider (e.g.: --config '{"aws_access_key_id":"my_access_key", "aws_secret_access_key":"my_secret_access_key"}')
Usage:
meroxa environments create NAME [flags]
Examples:
meroxa env create my-env --type hosted --provider aws --region …

Environment create example doesn't work copy-paste'd

---

.github/workflows/velocity_metrics.yml

For issue https://github.com/meroxa/infra/issues/454:
This change adds [github-action-datadog-reporting](
https://github.com/scribd/github-action-datadog-reporting) to this repository.
* Repo Velocity (Prefix `github_action_reporting.repo_velocity`):
* PR time to open
* PR time to merge
* PR lines changed

Add repo velocity reporting

---

docs/metrics.md

Adds https://github.com/meroxa/cli/blob/document-cased/docs/metrics.md so at least we have a place where we document how CLI metrics are used and configured.

doc: Add documentation on CLI metrics

---

cmd/meroxa/root/environments/create.go
cmd/meroxa/root/environments/create_test.go

The current format for a config flag (and metadata) can be a bit error prone, so switching that to a string array format.
Also, introducing default values for environment create flags.
If we like it, can consider rolling out to other commands.
- [X ]  Unit Tests
```
Flags:
-c, --config string     environment configuration based on type and provider (e.g.: --config '{"aws_access_key_id":"my_access_key", "aws_secret_access_key":"my_secret_access_key"}')
```
```
Flags:
-c, --config strings    environment configuration based on type and provider (e.g.: --config aws_access_key_id=my_access_key --config aws_access_secret=my_access_secret)
```

Tweak environment flags

---

cmd/meroxa/root/environments/create.go

Fix outdated help instructions for env create 
```
meroxa env create --help                                                                                                                                                  
Create an environment
Usage:
meroxa environments create NAME [flags]
Examples:
meroxa env create my-env --type self_hosted --provider aws --region us-east-1 --config "{\"aws_access_key_id\":\"my_access_key\", \"aws_secret_access_key\":\"my_secret_access_key\"}"
```
```
meroxa env create --help
Create an environment
Usage:
meroxa environments create NAME [flags]
Examples:
meroxa env create my-env --type self_hosted --provider aws --region us-east-1 --config aws_access_key_id=my_access_key …
```

Update example for env create

---

cmd/meroxa/root/environments/create_test.go
utils/display.go
utils/display_test.go

*A brief description of the change, what it is and why it was made.*
Fixes https://github.com/meroxa/cli/issues/229
Fixes https://github.com/meroxa/cli/issues/230
- [X ]  Bug fix
- [ X]  Unit Tests
$ m pipeline describe jtnewname
UUID:   9b16822d-a546-4cf8-be6b-300471f6dab2 
ID:   2961                                 
Name:   jtnewname                            
State:   Healthy                              
$ m connector describe mongodb-connector
UUID:   a69160c7-0014-40e7-a953-fe5042876ebe        
ID:   5532                                        
Name:   mongodb-connector                           
Type:   debezium-mongo-source                       
Streams:   (output) resource-6633-459461.meroxa.meroxa 
State:   pending …

Show common environment when no environment provided

---

cmd/meroxa/root/environments/list_test.go
cmd/meroxa/root/functions/create.go
cmd/meroxa/root/functions/create_test.go
cmd/meroxa/root/functions/describe.go
cmd/meroxa/root/functions/functions.go
cmd/meroxa/root/functions/list.go
cmd/meroxa/root/functions/remove.go
cmd/meroxa/root/root.go
go.mod
go.sum
utils/display.go
utils/display_test.go
utils/tests.go
vendor/github.com/mattn/go-shellwords/.travis.yml
vendor/github.com/mattn/go-shellwords/LICENSE
vendor/github.com/mattn/go-shellwords/README.md
vendor/github.com/mattn/go-shellwords/go.test.sh
vendor/github.com/mattn/go-shellwords/shellwords.go
vendor/github.com/mattn/go-shellwords/util_posix.go
vendor/github.com/mattn/go-shellwords/util_windows.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/environment.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/function.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/pipeline.go
vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
vendor/modules.txt

Add `meroxa functions`. This depends on https://github.com/meroxa/meroxa-go/pull/90.
```
$ m function create o-func --input-stream resource-4497-028165-users --image meroxa/funtime-example-jq --pipeline default --env JQ_QUERY=.
Function "o-func" successfully created!
$ m function list
UUID                    NAME            INPUT STREAM                    OUTPUT STREAM               STATE    PIPELINE
====================================== ========= ============================ ==================================== ========= ==========
85e18535-1505-4fe4-97cb-da209687b597   o-func    resource-4497-028165-users   resource-4497-028165-users-o-func    running   default
$ m function describe o-func
UUID:   85e18535-1505-4fe4-97cb-da209687b597
Name:   o-func
Input Stream: …
```

Add `meroxa functions`

---

.github/pull_request_template.md

This updates the PR templates to reflect the PR instructions as comments in the template instead of plain text. This way, the PR creator doesn't need to delete the instructions anymore before saving the description.
Tested manually on Github
|--|--|
|![Screen Shot 2022-02-01 at 11 30 42 AM](https://user-images.githubusercontent.com/8811742/151952710-d35a6457-ddc1-44e8-87fa-96b444b8de5a.png)|![pr-after](https://user-images.githubusercontent.com/8811742/151952551-70119a0c-27f6-46f4-8621-85e63b466e61.gif)|

upd(templates): move PR instructions into comments

---

cmd/meroxa/global/metrics_test.go

This fixes up a small linter error on the CLI.
```bash
$ golangci-lint run
 cmd/meroxa/global/metrics_test.go:96:18: dynamicFmtString: use errors.New(err) or fmt.Errorf('%s', err) instead (gocritic)
addError(event, fmt.Errorf(err))
```

fix(lint): update linting in metrics-test

---

cmd/meroxa/root/environments/environments.go
cmd/meroxa/root/environments/repair.go
cmd/meroxa/root/environments/repair_test.go
go.mod
go.sum
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/environment.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
vendor/modules.txt

Closes https://github.com/meroxa/cli/issues/184
This adds the `meroxa environment repair` command to the CLI.
**Staging**
|![meroxa-repair-error](https://user-images.githubusercontent.com/8811742/151976493-d3106820-b364-4414-9c50-0f936c79dc1d.gif)
**Locally**
Related to https://github.com/meroxa/platform-api/pull/811
Related to https://github.com/meroxa/meroxa-go/pull/92
Environment Implementation Plan (CLI): https://www.notion.so/meroxa/Environment-Implementation-Plan-Stage-2-60970cbce0a44c2b9095c0fea4172a69#7bc7dded7ae44b4e9fcd6e27ad189bba
Environment Implementation Plan (Client-API): https://www.notion.so/meroxa/Environment-Implementation-Plan-Stage-2-60970cbce0a44c2b9095c0fea4172a69#261d954133834d088323bfa6867375c1
Since the feature is still hidden, this change does not include any …

feat(repair): allow users to repair environments

---

cmd/meroxa/root/environments/repair.go

Fixes https://github.com/meroxa/cli/issues/253
####before
$ m env
Manage environments on Meroxa
Usage:
meroxa environments [command]
Aliases:
environments, env, environment
create      Create an environment
describe    Describe environment
list        List environments
remove      Remove environment
update      Update an environment
Flags:
-h, --help   help for environments
Global Flags:
--cli-config-file string   meroxa configuration file
--debug                    display any debugging information
--json                     output json
--timeout duration         set the duration of the client timeout in seconds (default 10s)
Use "meroxa environments [command] --help" for more information about a command.
####after
$m env
Manage environments on Meroxa
Usage:
meroxa …

bug(environments): Expose the env repair command

---

docs/cmd/md/meroxa_environments.md
docs/cmd/md/meroxa_environments_repair.md
docs/cmd/www/meroxa-environments-repair.md
docs/cmd/www/meroxa-environments.md
etc/completion/meroxa.completion.sh
etc/man/man1/meroxa-environments-repair.1

Follow up of https://github.com/meroxa/cli/pull/254
These will be part of https://github.com/meroxa/meroxa-docs/pull/72.

chore(environments): Add missing docs

---

cmd/meroxa/root/functions/functions.go
cmd/meroxa/root/functions/logs.go
go.mod
go.sum
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/log.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
vendor/modules.txt

Add `meroxa functions log`.
Fixes https://github.com/meroxa/cli/issues/244.

Add `meroxa functions log`

---

cmd/meroxa/root/apps/init.go
cmd/meroxa/root/apps/init_test.go
go.mod
go.sum
vendor/github.com/meroxa/turbine/init/template/.gitignore
vendor/modules.txt

…alize
Fixes https://github.com/meroxa/turbine-project/issues/76

feat(apps): Absorb turbine changes to create a .gitignore when doing git initialize

---

cmd/meroxa/root/apps/deploy.go

Fixes https://github.com/meroxa/turbine-project/issues/70

feat(turbine): Warn about uncommitted changes

---

cmd/meroxa/root/apps/init.go

Fixes https://github.com/meroxa/cli/issues/278
This re-enables the "go" shorthand parameter for initializing Turbine apps on the CLI.
|![appinitgo](https://user-images.githubusercontent.com/8811742/158659941-ce107fed-63a3-454c-bfae-0ec29eaf85b5.gif)|tbd|

fix(apps:init): re-enable language "go" shorthand on apps init

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/init.go
cmd/meroxa/root/apps/run.go
cmd/meroxa/turbine_cli/utils.go

Only the path flag on run was being interpreted as absolute, and not init or deploy. 
Fixes https://github.com/meroxa/turbine-project/issues/99

bug(turbine): Path should always be converted to absolute

---

cmd/meroxa/root/connectors/connect_test.go
cmd/meroxa/root/connectors/create.go
cmd/meroxa/root/connectors/create_test.go
cmd/meroxa/root/connectors/describe_test.go
cmd/meroxa/root/connectors/list.go
cmd/meroxa/root/connectors/list_test.go
cmd/meroxa/root/connectors/remove_test.go
cmd/meroxa/root/connectors/update_test.go
cmd/meroxa/root/pipelines/create.go
cmd/meroxa/root/pipelines/create_test.go
cmd/meroxa/root/pipelines/list_test.go
cmd/meroxa/root/pipelines/remove.go
cmd/meroxa/root/pipelines/remove_test.go
cmd/meroxa/root/pipelines/update.go
cmd/meroxa/root/pipelines/update_test.go
cmd/meroxa/root/resources/create.go
cmd/meroxa/root/resources/create_test.go
go.mod
go.sum
utils/display.go
utils/display_test.go
utils/tests.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/connector.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/environment.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/pipeline.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource.go
vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
vendor/modules.txt

Fixes https://github.com/meroxa/product/issues/225
depends on https://github.com/meroxa/meroxa-go/pull/105
|||

No longer expose or display IDs

---

cmd/meroxa/root/apps/init.go
cmd/meroxa/turbine_cli/golang/build.go
cmd/meroxa/turbine_cli/golang/deploy.go
cmd/meroxa/turbine_cli/golang/run.go
cmd/meroxa/turbine_cli/javascript/build.go
cmd/meroxa/turbine_cli/javascript/deploy.go
cmd/meroxa/turbine_cli/javascript/init.go
cmd/meroxa/turbine_cli/utils.go

We were relying on exit code from go or turbine apps.  should check stderr too
Fixes https://github.com/meroxa/turbine-project/issues/115

Use stderr and exit code to detect errors

---

cmd/meroxa/root/apps/apps.go
cmd/meroxa/root/apps/init.go
cmd/meroxa/turbine_cli/python/init.go

Adds `python` to `meroxa apps init` 
Fixes https://github.com/meroxa/turbine-project/issues/96
Running `meroxa apps init` with the python flag
App directory created at specified location with expected files and directories

Initiate Python application via apps init 

---

.circleci/config.yml

Follow-up to https://github.com/meroxa/cli/pull/288
I followed [this guide](https://circleci.com/docs/2.0/gh-bb-integration/#enable-your-project-to-check-out-additional-private-repositories) to add a machine user key to our cli project on CircleCI.
Example run on Circle CI: https://app.circleci.com/pipelines/github/meroxa/cli/1434/workflows/3b9d64d1-c8ee-4336-a98f-8b240cc0483c/jobs/1393
Manually on CircleCI

Allow downloads of private repositories during Circle CI runs

---

cmd/meroxa/root/apps/run.go
cmd/meroxa/turbine_cli/javascript/build.go
cmd/meroxa/turbine_cli/python/init.go
cmd/meroxa/turbine_cli/python/run.go
cmd/meroxa/turbine_cli/utils.go

because of the naming clash between turbine-js and turbine-py, initiatializing a py app made a js app.  also, error handling still wasn't quite right and calling run helps confirm all the right things are happening during init.
Fixes https://github.com/meroxa/turbine-project/issues/124
|||

Tweaks to init and run

---

cmd/meroxa/root/apps/init.go
cmd/meroxa/root/apps/init_test.go
cmd/meroxa/turbine_cli/utils.go

print the success log after git init
warn and skip go mod init if the given path is not within $GOPATH
update init go app example to include $GOPATH in the --path value
bonus:
make it clearer when the given path for app run or app deploy is not an app dir ... can't find name doesn't help the user fix the error quickly
Fixes https://github.com/meroxa/turbine-project/issues/128

UX improvements for go app init and path flag

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/turbine_cli/golang/build.go
cmd/meroxa/turbine_cli/golang/deploy.go
cmd/meroxa/turbine_cli/golang/run.go

Fixes https://github.com/meroxa/turbine-project/issues/134

Clearer logs around building and deploying go apps

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/turbine_cli/javascript/deploy.go
cmd/meroxa/turbine_cli/utils.go

Fixes https://github.com/meroxa/turbine-project/issues/139

Parse logs gracefully when deploying a javascript app

---

cmd/meroxa/turbine_cli/python/deploy.go
cmd/meroxa/turbine_cli/python/init.go

Fixes https://github.com/meroxa/turbine-project/issues/83
|||

feat(apps): Update python commands

---

cmd/meroxa/turbine_cli/javascript/deploy.go

CLI now expects a specific format when receiving responses from turbine-js. This allows us to only capture what we care about and leave the rest of the output alone. 
|||
See this thread https://meroxa.slack.com/archives/C02L14X6TA9/p1649879600763529
+ [ ] Merge https://github.com/meroxa/turbine-js/pull/58 at the same time

Define contract for turbine response and capture

---

cmd/meroxa/root/apps/apps.go
cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/describe.go
cmd/meroxa/root/apps/init.go
cmd/meroxa/root/apps/list.go
cmd/meroxa/root/apps/remove.go
cmd/meroxa/root/apps/run.go
docs/cmd/md/meroxa.md
docs/cmd/md/meroxa_apps.md
docs/cmd/md/meroxa_apps_deploy.md
docs/cmd/md/meroxa_apps_describe.md
docs/cmd/md/meroxa_apps_init.md
docs/cmd/md/meroxa_apps_list.md
docs/cmd/md/meroxa_apps_remove.md
docs/cmd/md/meroxa_apps_run.md
docs/cmd/www/meroxa-apps-deploy.md
docs/cmd/www/meroxa-apps-describe.md
docs/cmd/www/meroxa-apps-init.md
docs/cmd/www/meroxa-apps-list.md
docs/cmd/www/meroxa-apps-remove.md
docs/cmd/www/meroxa-apps-run.md
docs/cmd/www/meroxa-apps.md
docs/cmd/www/meroxa.md
etc/man/man1/meroxa-apps-deploy.1
etc/man/man1/meroxa-apps-describe.1
etc/man/man1/meroxa-apps-init.1
etc/man/man1/meroxa-apps-list.1
etc/man/man1/meroxa-apps-remove.1
etc/man/man1/meroxa-apps-run.1
etc/man/man1/meroxa-apps.1

Update to the right product name.
https://github.com/meroxa/meroxa-docs/pull/91

chore: Update product name

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go

Fixes https://github.com/meroxa/turbine-project/issues/173

fix: always use app name defined in app.json

---

go.mod
go.sum
vendor/github.com/meroxa/meroxa-go/LICENSE.md
vendor/github.com/meroxa/turbine-go/LICENSE.md
vendor/github.com/meroxa/turbine-go/init/template/app.go
vendor/modules.txt

This upgrades to the latest version of turbine-go, including https://github.com/meroxa/turbine-go/pull/36

upd(turbine-go): upgrade turbine-go and meroxa-go to latest version

---

cmd/meroxa/turbine_cli/javascript/build.go
cmd/meroxa/turbine_cli/javascript/deploy.go
cmd/meroxa/turbine_cli/javascript/init.go

Updates the name of the turbine-js executable to the public name of the package 
|||

Update turbine-js command name

---

cmd/meroxa/root/resources/create.go
docs/cmd/md/meroxa_resources_create.md
docs/cmd/www/meroxa-resources-create.md
etc/man/man1/meroxa-resources-create.1

If you do what was in the example, it actually doesn't add a Postgres DB with logical replication enabled.
In other words, connectors using this as a source until now they remained as `jdbc-source` and not `debezium-pg-source`.
- Testing turbine go app with logical replication, I noticed this.
https://github.com/meroxa/meroxa-docs/pull/101

fix: documentation for logical replication

---

Makefile
cmd/meroxa/main.go

Fixes https://github.com/meroxa/cli/issues/340
**Before**
```
$ make install
$ meroxa version
meroxa/dev darwin/amd64
```
**After**
```
$ make install
$ meroxa version
meroxa/dev:7abf3288 v2.0.0-alpha.3-1-g7abf3288 darwin/amd64
```
If a change was made on top of a commit:
```
$ meroxa version
meroxa/dev:7abf3288 v2.0.0-alpha.3-1-g7abf3288 (updated) darwin/amd64
```
If it was built from same source as a tag:
```
$ meroxa version
meroxa/dev:7abf3288 v2.0.0-alpha.3 darwin/amd64
```
**Note:** Demo was shared in slack if you still need more info.

feat: Include dev info on meroxa version

---

cmd/meroxa/main.go

Fixes wrong formatting of version when using a CLI distributed. Brought by https://github.com/meroxa/cli/pull/341
**Before**
```
$ meroxa version
meroxa/2.0.1:   darwin/amd64
```
**After**
```
$ meroxa version
meroxa/2.0.1  darwin/amd64
```

fix: version formatting

---

cmd/meroxa/root/apps/apps.go
cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/init.go
cmd/meroxa/root/apps/run.go

We have noticed some customer attempting to use `python3` as one of the languages. 
Adding "support" for this option is fairly trivial and we should do that since documentation uses `python` and `python3` interchangeably.
**Before**
```
$ meroxa apps init --lang python3
language "python3" not supported. Currently, we support "javascript", "golang", and "python"
```
**Now**
```
$ meroxa apps init --lang python3
Initializing application...
```

feat: Add support to python3 as possible option

---

cmd/meroxa/root/apps/init.go

Customers may not immediately understand that the init command doesn't make any API calls and the dashboard won't show the app yet
Fixes https://github.com/meroxa/turbine-project/issues/246
|||

Provide clarity on how the init command and dashboard interact

---

.github/workflows/release.yml

Fixes the following experience:
```
$ brew upgrade meroxa
/.../
==> Upgrading meroxa/taps/meroxa
1.6.3-alpha.1 -> 2.1.0-nightly.20220514
```

feat: Only release to homebrew not nightly builds

---

.github/workflows/golangci-lint.yml
.goreleaser.yml
cmd/meroxa/builder/autoupdate.go
cmd/meroxa/builder/autoupdate_test.go
cmd/meroxa/builder/builder.go
cmd/meroxa/builder/builder_test.go
cmd/meroxa/github/github.go
cmd/meroxa/github/github_test.go
cmd/meroxa/global/global.go
cmd/meroxa/main.go
cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/describe.go
cmd/meroxa/root/config/config.go
cmd/meroxa/root/config/set.go
cmd/meroxa/root/config/set_test.go
docs/cmd/md/meroxa_config.md
docs/cmd/md/meroxa_config_set.md
docs/cmd/www/meroxa-config-set.md
docs/cmd/www/meroxa-config.md
etc/completion/meroxa.completion.sh
etc/man/man1/meroxa-config-set.1
etc/man/man1/meroxa-config.1

- Fixes https://github.com/meroxa/product/issues/121 
**First time or once a week**
```
$ meroxa whoami 
raul@meroxa.io
🎁 meroxa v2.1.1 is available! Update it by running: `brew upgrade meroxa`
🧐 Check out latest changes in https://github.com/meroxa/cli/releases/tag/v2.1.1
💡 To disable these warnings, run `meroxa config set DISABLE_NOTIFICATIONS_UPDATE=true`
````
**Disable notifications on update**
```
$ meroxa config set disableNotificationsUpdate=true
Updating your Meroxa configuration file with DISABLE_NOTIFICATIONS_UPDATE=true...
Done!
```
- You can also update several keys at once:
```
$ meroxa config set disableNotificationsUpdate=true latestCliVersionUpdatedAt=
Updating your Meroxa configuration file with LATEST_CLI_VERSION_UPDATED_AT=...
Updating your Meroxa configuration file …
```

feat: Automatic version update warnings + new `config set` cmd

---

go.mod
go.sum
vendor/modules.txt

The following commands were run to generate changes: go get -u github.com/meroxa/turbine-go@latest and make gomod

chore: Upgrade to latest turbine-go

---

cmd/meroxa/turbine_cli/utils.go
cmd/meroxa/turbine_cli/utils_test.go

See 
https://meroxa.slack.com/archives/C02L14X6TA9/p1658353954803519
Eric was running into an issue with local dev setup which led me down an interesting path of discovering some odd behavior with bin naming. I believe this is due to something specific about the way that asdf installs global packages wrt bin filenames. 
This updates us to always use `turbine-js` as the name for the local executable, instead of `turbine`, which is the most correct name according to https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bin and should work for everyone regardless of version manager (or lack of).

Use `turbine-js` for local bin name

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/turbine_cli/local_deployment.go
go.mod
go.sum
vendor/github.com/meroxa/turbine-go/.gitignore
vendor/github.com/meroxa/turbine-go/Makefile
vendor/github.com/meroxa/turbine-go/config.go
vendor/github.com/meroxa/turbine-go/deploy/deploy.go
vendor/modules.txt

Changes to how the dockerfile is generated in turbine go need to translated to the CLI.
|||

Update latest turbine-go

---

cmd/meroxa/root/api/api.go
cmd/meroxa/root/api/api_test.go
cmd/meroxa/root/apps/init.go
cmd/meroxa/root/apps/init_test.go
cmd/meroxa/turbine_cli/utils.go
go.mod
go.sum
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/application.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/build.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/connector.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/endpoint.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/environment.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/function.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/log.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/pipeline.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource_types.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/source.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/transform.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/user.go
vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
vendor/modules.txt

Updating `meroxa-go` package to be able to inject headers in the `apiClient.MakeRequest` calls.
_Extra: GOPATH was required for the app's initialization, and `build.Default.GOPATH` was added as a fallback._

Meroxa go upgrade headers

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/turbine_cli/python/deploy.go
cmd/meroxa/turbine_cli/utils.go

Changes as part of feature branch project for turbine-py. List resources on turbine-py now dumbs json similar to go, the code for parsing is now the same as for golang too. 
Deploy also now requires an app name, this will be using to override app.json app_name. 
Fixes (https://github.com/meroxa/product/issues/398)
Relevant PRs: 
https://github.com/meroxa/turbine-py/pull/80
https://github.com/meroxa/meroxa-py/pull/34

Turbine-py feature branch changes (--listresources and app name)

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/turbine_cli/javascript/deploy.go
cmd/meroxa/turbine_cli/utils.go

Changes as part of feature branch project for turbine-js. List resources on turbine-js now dumbs json similar to go, the code for parsing is now the same as for golang too. 
Deploy also now requires an app name, this will be using to override app.json app_name. 
Fixes (https://github.com/meroxa/product/issues/398)
Relevant PRs: 
https://github.com/meroxa/turbine-js/pull/121
https://github.com/meroxa/meroxa-js/pull/23

Turbine-js feature branch changes (--listresources and app name)

---

Makefile
cmd/meroxa/root/apps/deploy.go
cmd/meroxa/turbine_cli/utils.go

Use go commands native way to switch to a folder when executing a command. 
Add functionality stub to prepare app name. Isolate validation to determine if the a branch is either `main` or `master`.
Part of https://github.com/meroxa/product/issues/502
|||

Refactor turbine cli utils

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/turbine_cli/javascript/deploy.go
cmd/meroxa/turbine_cli/utils.go
cmd/meroxa/turbine_cli/utils_test.go

+ Support separated packages from https://github.com/meroxa/turbine-js/pull/115 
+ `meroxa-js-cli`
+ `meroxa-js-framework`
+ Remove temporary directory building from turbine-js apps. Turbine-js apps now build just like turbine-go minus creating a binary
+ Meroxa cli calls turbine-js-cli to copy dockerfile from package to app directory
+ Meroxa cli tar/uploads app directory
+ Meroxa cli cleans up dockerfile
https://github.com/meroxa/turbine-js/pull/115

Support turbine-js package build, remove temp dir build

---

cmd/meroxa/root/apps/deploy.go

New app name was not reported during feature branch deploy
|<img width="764" alt="Screen Shot 2022-08-18 at 6 11 58 PM" src="https://user-images.githubusercontent.com/31331000/185504192-61c4196d-6eaf-4cf6-89f9-2cbf41d852f8.png"> |<img width="966" alt="Screen Shot 2022-08-18 at 6 12 55 PM" src="https://user-images.githubusercontent.com/31331000/185504292-f9c246b1-1197-4eb5-a626-fa9303c9e709.png">|

Report app name when feature branch detected

---

cmd/meroxa/root/apps/init.go
cmd/meroxa/root/apps/init_test.go
cmd/meroxa/turbine/golang/init.go
cmd/meroxa/turbine/golang/utils.go
cmd/meroxa/turbine/interface.go
cmd/meroxa/turbine/javascript/init.go
cmd/meroxa/turbine/mock/cli.go
cmd/meroxa/turbine/python/init.go
cmd/meroxa/turbine/utils.go
cmd/meroxa/turbine/utils_test.go

Use the turbine CLI interface in the init command so as to test the command without accessing the filesystem or calling other binaries as much as possible
the existing test for Go init is pretty thorough and tests a number of functions, so leaving it there for now and may move it around in a PR that is coming soon
Related to meroxa/turbine-project#251
|||

Update init command and its tests to use the turbine CLI interface

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go

Ali brought up a case that would require skipping looping validation https://meroxa.slack.com/archives/C02ECHVCHSA/p1661444080066859?thread_ts=1661440392.621599&cid=C02ECHVCHSA
So we want to modify the old skip flag to also skip all collection validation 
Before:
```
➜  test-go git:(feature-branch) meroxa apps deploy --skip-unique-collection
✔ Checked your language is "python"
✔ Checked your application name is "test-py"
Deploying application "test-py"...
✔ Application built
x Resource availability check failed
Error: ⚠️
Application resource "pg" with collection "sequences" cannot be used as a destination. It is also the source.
Please modify your Turbine data application code. …
```

Allow to skip all collection validations

---

cmd/meroxa/root/apps/init.go

any combination of capital letters in the language name should be acceptable
Fixes https://github.com/meroxa/product/issues/541
BEFORE
$ m apps init --lang GoLang capitalization
x 	
Error: language "GoLang" not supported. Currently, we support "javascript", "golang", and "python"
AFTER
$ m apps init --lang GoLang capitalization
✔ Application directory created!
✔ go mod init succeeded!
✔ Downloaded latest turbine-go and turbine-go/running dependencies successfully!
✔ Downloaded all other dependencies successfully!
✔ Git initialized successfully!
Turbine Data Application successfully initialized!
You can start interacting with Meroxa in your app located at "/home/janelle/go/src/github.com/meroxa/demos/capitalization".
Your Application will not be visible in the Meroxa Dashboard until after …

Ignore capitalization when initializing an app

---

cmd/meroxa/turbine/javascript/deploy.go

Fixes the hasfunctions command to use the app path and not the app name. 

Make sure `hasfunctions` via turbine-js uses app path

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go
cmd/meroxa/turbine/golang/deploy.go
cmd/meroxa/turbine/interface.go
cmd/meroxa/turbine/javascript/deploy.go
cmd/meroxa/turbine/mock/cli.go
cmd/meroxa/turbine/python/deploy.go
cmd/meroxa/turbine/utils.go
go.mod
go.sum
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/application.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/deployment.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/resource_types.go
vendor/github.com/meroxa/meroxa-go/pkg/mock/mock_client.go
vendor/modules.txt

Fixes https://github.com/meroxa/product/issues/544
|||

[IR] accommodate preIR and IR deployments side by side

---

cmd/meroxa/turbine/utils.go

This bumps the turbine-js-cli dependency to the latest tag to include the following changes required for using confluentcloud in Turbine apps:
- https://github.com/meroxa/turbine-js/pull/159
- https://github.com/meroxa/meroxa-js/pull/26
|||
https://meroxa.slack.com/archives/C01SNJCR9RP/p1664300918706029

deps(turbine-js): bump to latest patch version of turbine-js-cli@1.2.0

---

cmd/meroxa/root/apps/logs.go
cmd/meroxa/root/apps/logs_test.go
utils/display/apps.go
utils/display/apps_test.go

Fixes https://github.com/meroxa/product/issues/552
Note: 
- connector and function logs were shortened for purpose of example
- function name is not present, and resource name is used instead
```
➜  cli git:(master) meroxa apps logs test-app
important-data (source)
[2022-09-30T18:25:38Z] Executing prepared statement with incrementing value = 11[2022-09-30T18:25:38Z] Resetting querier TimestampIncrementingTableQuerier{table="public"."sequences", query='null', topicPrefix='resource-2-104604-', incrementingColumn='id', timestampColumns=[]}[2022-09-30T18:25:43Z] Checking for next block of results from TimestampIncrementingTableQuerier{table="public"."sequences", query='null', topicPrefix='resource-2-104604-', 
...
pg (destination)
[2022-09-30T18:14:23Z] Attempting to open connection #1 to …
```

Include deployment output logs in app logs

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go
go.mod
go.sum
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/deployment.go
vendor/modules.txt

Ensure deployment spec is json
Currently, cli sends the spec as a string json, and not a json blob:
```
"{\"connectors\":[{\"type\":\"source\",\"resource\":\"pg\",\"collection\":\"sequences\"},{\"type\":\"destination\",\"resource\":\"pg\",\"collection\":\"sequences_greeting\"}],\"definition\":{\"git_sha\":\"353b34ac6917dcdb10cc00b74010f9222914518c\\n\",\"metadata\":{\"turbine\":{\"language\":\"golang\",\"version\":\"1.19.1\"},\"spec_version\":\"0.1.1\"}}}"
```
We want the json to be parsed into a json blob instead:
```
{"connectors": [{"type": "source", "resource": "pg", "collection": "sequences"}, {"type": "destination", "resource": "pg", "collection": "sequences_greeting"}], "definition": {"git_sha": "353b34ac6917dcdb10cc00b74010f9222914518c\n", "metadata": {"turbine": {"version": …
```

Ensure deployment spec is json

---

cmd/meroxa/root/auth/login.go

This in fact is not working. After a bit of investigation, I couldn't figure out the root cause. Considering this is not highly critical, I think it's best simply update the wording for now.
- In different web browsers.
**Before**
**After this PR**
Reported by @hariso in our #CLI slack channel.

fix: wrong auto-close message

---

go.mod
go.sum
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/meroxa.go
vendor/modules.txt

Pulls in updated meroxa-go that properly sets account-uuid header
Fixes https://github.com/meroxa/cli/issues/476
$ m accounts ls --debug
GET /v1/accounts HTTP/1.1
Host: api.staging.meroxa.io
User-Agent: Meroxa CLI dev:cb9fd579 v2.9.0-nightly.20221013-1-gcb9fd579 (updated)
Accept: application/json
Authorization: Bearer eyJhbGc...hpzNhhQ
Content-Type: application/json
Accept-Encoding: gzip
HTTP/2.0 200 OK
Content-Length: 121
Content-Type: application/json; charset=utf-8
Date: Thu, 13 Oct 2022 14:55:30 GMT
Meroxa-Request-Id: 0881ce91-e8de-4f97-81fb-06d21eb13bcc
Set-Cookie: _gorilla_csrf=MTY2NTY3MjkzMHxJbWw0TjFWeWRDOHpZa0pRWWl0RVVYQkVWWFZyZVZOcU9HUjRUbEJEYlZOc1drdGhORGRoVXpKcWJqQTlJZ289fP54cDseFTLjJnQm8vrMztCDdDh1pjQtVjxyOmzxrumz; Path=/; Expires=Fri, 14 Oct 2022 02:55:30 GMT; Max-Age=43200; …

fix: missing account header

---

cmd/meroxa/root/apps/logs.go

Do not require feature flags for apps logs
Fixes https://github.com/meroxa/cli/issues/487
BEFORE
AFTER

fix: restore apps logs without IR

---

cmd/meroxa/turbine/utils.go

Fixes double write of git sha in fn name by pulling in latest turbine-js
|||

fix: bump turbine-js to 1.3.3

---

cmd/meroxa/root/apps/logs.go

App logs command errors when deployment doesn't exist
```
meroxa apps deploy --spec "0.1.1"
✔ Checked your language is "golang"
✔ Checked your application name is "test-go"
Preparing to deploy application "test-go"...
x # meroxa/test-go
./app.go:33:23: undefined: Append0er
warning: failed to clean up /Users/dianadoherty/go/src/meroxa/test-go/test-go
warning: failed to clean up /Users/dianadoherty/go/src/meroxa/test-go/test-go.cross
Error: build failed
```
```
meroxa apps logs test-go    
Error: could not find deployment
```
```
meroxa apps logs test-go
```
cli doesn't error, but still reports no longs since none of the artifacts were created

Don't error on app logs if deployment not found

---

cmd/meroxa/turbine/utils.go

We may be able to avoid failing a deployment by retrying an upload to AWS
Fixes https://github.com/meroxa/product/issues/501
|=== RUN   TestAppSecurity/deploy_vulnerability_detecting_Go_App
security_test.go:179: /app/bin/meroxa --cli-config-file /root/meroxa.env app deploy --path /apps/security/ --json
security_test.go:179: 	✔ Checked your language is "golang"
✔ Checked your application name is "security3umrzkxsfftnxtpesg01"
✔ Deployment allowed from "master" branch
✔ Application built
✔ Can access to your Turbine resources
✔ Application processes found. Creating application image...
✔ Platform source fetched
✔ Dockerfile created
✔ "turbine-security3umrzkxsfftnxtpesg01.tar.gz" successfully created in "/apps/security"
x 	 Failed to send PUT request
✔ …

Retry uploading build source file to AWS three times

---

cmd/meroxa/turbine/golang/deploy.go

An empty set is interpreted as at least 1, and a function build occurs unnecessarily.
BEFORE
AFTER

fix: Drop brackets before assessing how many functions there are in a Go app

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go
cmd/meroxa/turbine/golang/deploy.go
cmd/meroxa/turbine/javascript/deploy.go
cmd/meroxa/turbine/python/deploy.go
cmd/meroxa/turbine/python/upgrade.go
cmd/meroxa/turbine/utils.go

Fixes https://github.com/meroxa/product/issues/559
**Before**
Regular deployment (pre: intermediate representation)
```
$ meroxa apps deploy .
```
To use a deployment using Intermediate representation:
```
$ meroxa apps deploy . --spec 0.1.1
```
**After**
To use a deployment using Intermediate representation, it'll fetch latest version and it'll be sent to all turbine libraries.
```
$ meroxa apps deploy .
```
This will be a nice to have right after we ship this pull-request to prevent unexpected behavior coming from old libraries: https://github.com/meroxa/product/issues/598.
A changelog will be needed in https://github.com/meroxa/product/issues/593.

feat: make ir deployments default

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go
cmd/meroxa/root/apps/upgrade.go
cmd/meroxa/turbine/golang/build.go
cmd/meroxa/turbine/golang/init.go
cmd/meroxa/turbine/golang/upgrade.go
cmd/meroxa/turbine/golang/utils.go
cmd/meroxa/turbine/javascript/upgrade.go
cmd/meroxa/turbine/python/build.go
cmd/meroxa/turbine/python/upgrade.go
cmd/meroxa/turbine/utils.go
log/spinner.go

This pull request adds the `--verbose` flag (which will be hidden until we validate it with customers). 
**With `--verbose` on a successful deployment**
```
$ meroxa apps deploy --path ../../trash/simple-js/ --verbose
✔ Checked your language is "javascript"
✔ Checked your application name is "simple-js-ir"
Preparing to deploy application "simple-js-ir"...
✔ Can access your Turbine resources
✔ No need to create process image
Deploying application "simple-js-ir"...
successfully validated application pipeline
failed to create source connector
✔ Application "simple-js-ir" successfully deployed!
✨ To visualize your application visit https://dashboard.meroxa.io/apps/simple-js-ir/detail
```
**Without …

feat: add hidden verbose flag to apps deploy to show more logs

---

cmd/meroxa/turbine/utils.go
cmd/meroxa/turbine/utils_test.go

Error: Put "https://meroxa-source-d419bd4a-2984-4126-937b-7cbabdeac6c8.s3.amazonaws.com/9d7d7837-1a9e-4f17-b25f-8669359692bf.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAUCRKS4PCXOMDXBBO%2F20221102%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221102T153607Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=590786ecb11cc452b63bf00879775726c87107bf266a1e8a8d88492daa7bbce0": read turbine-go-acceptance-app-c6e0e801-7fc8-4194-af51-2a2aeb97bb1b.tar.gz: file already closed
See this error regularly from the acceptance tests
Fixes https://github.com/meroxa/cli/issues/524
|||

File descriptor will be closed after calling Do()

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go
cmd/meroxa/turbine/golang/deploy.go
cmd/meroxa/turbine/javascript/deploy.go
cmd/meroxa/turbine/python/deploy.go

Deploying using IR is still possible via `--spec 0.1.1`
**Before**
```
$ meroxa apps deploy . 
// deploy using IR
```
**Now**
```
$ meroxa apps deploy . 
// deploy using pre-IR
$ meroxa apps deploy . --spec 0.1.1 
// deploy using IR
```

feat: make non ir deployments default

---

go.mod
go.sum
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/api_errors.go
vendor/modules.txt

Update meroxa-go version that refactors error message
Fixes https://github.com/meroxa/meroxa-go/issues/142
|||

Update meroxa-go version that refactors error message

---

cmd/meroxa/turbine/ruby/build.go
cmd/meroxa/turbine/ruby/cli.go
cmd/meroxa/turbine/ruby/deploy.go
cmd/meroxa/turbine/ruby/init.go
cmd/meroxa/turbine/ruby/run.go
cmd/meroxa/turbine/ruby/upgrade.go
cmd/meroxa/turbine/utils.go

Stubs for turbine-ruby cli. Contains functions needed by interfaces 
https://github.com/meroxa/cli/blob/a3f45174615af714697d5cf043dd8751d3bbb831/cmd/meroxa/turbine/interface.go#L7
Fixes https://github.com/meroxa/cli/issues/521

Turbine-Ruby CLI Stub 

---

cmd/meroxa/root/apps/describe.go

Point customers to the Dashboard to visualize in more places
Fixes https://github.com/meroxa/cli/issues/535
|
|
|

Add link to dasboard from 'apps describe' output

---

cmd/meroxa/turbine/golang/version.go
cmd/meroxa/turbine/interface.go
cmd/meroxa/turbine/javascript/version.go
cmd/meroxa/turbine/mock/cli.go
cmd/meroxa/turbine/python/version.go
cmd/meroxa/turbine/ruby/version.go

Determine the version of turbine-go used in an App
make grabbing all versions of turbine libs used in an App accessible
Fixes https://github.com/meroxa/turbine-project/issues/266
|||

Add version function for each turbine library

---

cmd/meroxa/root/apps/run_test.go
cmd/meroxa/turbine/ruby/internal/cmd.go
cmd/meroxa/turbine/ruby/internal/cmd_test.go

Fixes flapping test in `apps run` for ruby and renames `Turbine` to `TurbineRb`
|||

Fix flapping test and rename TurbineRb

---

cmd/meroxa/turbine/utils.go

Npm logs are sent to stderr and need to be processed especially to ignore most of them.
Fixes https://github.com/meroxa/turbine-project/issues/145
$ npm config set loglevel=info
$ m apps init --lang js --path ~/go/src/github.com/meroxa/jsdemos warntest4
⠦ Initializing application "warntest4" in "/home/janelle/go/src/github.com/meroxa/jsdemos"...err: <nil>
stdout: 
stderr: npm info using npm@8.19.2
npm info using node@v16.17.0
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 4ms
npm timing config:load:builtin Completed in 4ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing …

Ignore low level logs from npm

---

cmd/meroxa/root/apps/init.go
cmd/meroxa/root/apps/run.go
cmd/meroxa/root/apps/upgrade.go

=== RUN   TestAppMgmt/GO:_Run_app#01
shared_test.go:164: /app/bin/meroxa --cli-config-file /root/meroxa.invited.env app run --path /apps/turbine_go/tmp/app/go-acceptance-app-2d055645-2cc9-481f-9e51-7b6a6fd21297 --json
shared_test.go:166: Error: no access to the Meroxa Turbine Ruby feature.
Sign up for the Beta here: https://share.hsforms.com/1Uq6UYoL8Q6eV5QzSiyIQkAc2sme
turbine_test.go:410: exit status 1
run on a go app is being blocked on a lack of feature flag for ruby
|||

Do not gate the whole command on the ruby feature flag

---

cmd/meroxa/turbine/utils.go

x 	The final step to 'git init' the Application repo failed. Please complete this step manually.
Error: warning: init.defaultbranch has multiple values
error: cannot overwrite multiple values with a single value
Use a regexp, --add or --replace-all to change init.defaultBranch.
Setting the global config was a bit aggressive of us... just locally to the repo is better
|||

Git init failing

---

cmd/meroxa/turbine/javascript/cli.go
cmd/meroxa/turbine/javascript/deploy.go
cmd/meroxa/turbine/javascript/init.go
cmd/meroxa/turbine/javascript/run.go
cmd/meroxa/turbine/javascript/version.go

Not all turbine-js-* commands were getting npm logs filtered out
Related to https://github.com/meroxa/turbine-project/issues/145
|||

Filter npm logs from all npx calls

---

go.mod
go.sum
vendor/github.com/meroxa/turbine-core/pkg/ir/schema.json
vendor/github.com/meroxa/turbine-core/pkg/ir/spec.go
vendor/github.com/meroxa/turbine-core/pkg/server/record.go
vendor/modules.txt

Upgrade turbine-core version to ensure ruby is using 0.2.0 IR spec
Depends on https://github.com/meroxa/platform-api/pull/1580
```
{
"connectors": [
{
"uuid": "a20271e8-45eb-42bb-b7e5-0d71f07da353",
"type": "source",
"resource": "pg",
"collection": "sequences"
},
{
"uuid": "767801e7-96a5-47d3-9b72-054ca9606863",
"type": "destination",
"resource": "pg",
"collection": "testing1_no_fn_rb"
},
{
"uuid": "1dd8f613-1779-45bd-8c02-c37e8c47f561",
"type": "destination",
"resource": "pg",
"collection": "testing1_fn_rb"
}
],
"functions": [
{
"uuid": "af760fce-8ef0-4e9f-8146-4ec93140c170",
"name": "passthrough",
"image": "7131614c-0120-4277-8de5-d94447f07723"
}
],
"streams": [
{
"uuid": "57c58a10-3828-4e56-ad51-db35c548013d",
"name": …
```

Upgrade turbine-core version

---

cmd/meroxa/turbine/ruby/version.go

Testing a ruby application in staging noticed this issue.
**before**
```
$ meroxa apps deploy ...
✔ Checked your language is "ruby"
✔ Checked your application name is "ruby-example"
Error: unable to determine the turbine-rb version of the Meroxa Application at /Users/rb/code/meroxa/turbine-examples/ruby/simple
```
**after**
```
$ meroxa apps deploy ...
✔ Checked your language is "ruby"
✔ Checked your application name is "ruby-example"
...
```

fix: wrong gem name

---

cmd/meroxa/root/apps/apps.go
cmd/meroxa/root/apps/init.go
cmd/meroxa/root/apps/run.go
cmd/meroxa/root/apps/run_test.go
cmd/meroxa/root/apps/upgrade.go
cmd/meroxa/turbine/ruby/cli.go

Remove ruby feature flag
Fixes https://github.com/meroxa/product/issues/630
|<img width="1000" alt="Screenshot 2022-12-08 at 11 56 32 AM" src="https://user-images.githubusercontent.com/31331000/206515162-31bd994c-ebd2-430d-b959-997bd6ac182f.png">|<img width="1000" alt="Screenshot 2022-12-08 at 11 56 44 AM" src="https://user-images.githubusercontent.com/31331000/206515211-f60595e9-aa5c-4da5-a8b6-3afed8993729.png">|

Remove ruby feature flag

---

go.mod
go.sum
utils/display/apps.go
utils/display/apps_test.go
utils/tests.go
vendor/modules.txt

Fixes https://github.com/meroxa/cli/issues/592
⚠️ It's branched off https://github.com/meroxa/cli/pull/603
**Before**
```
$ meroxa app describe rubyapp   
UUID:   6c5e1c07-a42e-4079-85e1-efeceaae777f     
Name:   rubyapp                                  
Language:   ruby                                     
Git SHA:   a29551e15bdb9363edd319dee46403a4e4b4b6cd 
Created At:   2023-01-17 19:36:59 +0000 UTC            
Updated At:   2023-01-17 19:36:59 +0000 UTC            
State:   degraded                                 
Resources
dest (destination)
UUID:   04636b3d-1ccd-4a5a-bb2a-5969abb52395
Type:   postgres
State:   running
dest2 (destination)
UUID:   ceb130fa-3769-4796-8f47-a2471fa18a07
Type:   postgres
State:   running
source (source)
UUID:   bd295652-df7f-44ec-acf8-3a75e8d2e079
Type: …
```

feat(apps): Include environment info in `apps describe`

---

go.mod
go.sum
vendor/modules.txt

Bump to 2.8.1 
```
verifying github.com/docker/distribution@v2.8.0+incompatible: checksum mismatch
downloaded: h1:u9vuu6qqG7nN9a735Noed0ahoUm30iipVRlhgh72N0M=
go.sum:     h1:l9EaZDICImO1ngI+uTifW+ZYvvz7fKISBAKpg+MbWbY=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
For more information, see 'go help module-auth'.
```
See https://github.com/distribution/distribution/issues/3590
|||

Upgrade docker distribution

---

cmd/meroxa/root/apps/deploy.go

Pass env info on app deploy to api
App 1-2 were created without the change, apps 3-4 were created with the change in this PR 
```
meroxa-api=# select id, name, language, environment_uuid from application;
id |  name   | language |           environment_uuid           
----+---------+----------+--------------------------------------
1 | test-rb | ruby     | 
2 | test-rb | ruby     | 
3 | test-rb | ruby     | 9364f5ef-3b09-4b63-85f6-b9588c69f613
4 | test-rb | ruby     | 9364f5ef-3b09-4b63-85f6-b9588c69f613
```

Pass env info on app deploy to api

---

cmd/meroxa/root/environments/update.go
docs/cmd/md/meroxa_environments_update.md
docs/cmd/www/meroxa-environments-update.md
etc/man/man1/meroxa-environments-update.1

The referred config variable is incorrect.
Part of https://github.com/meroxa/platform-api/issues/1646
|||

Update help on env update

---

cmd/meroxa/root/resources/list.go
cmd/meroxa/root/resources/list_test.go
utils/display/resources.go
utils/display/resources_test.go

Update the resource type list format to display type name and release stage
provide a link to the Resource Catalog in the Dashboard
Fixes https://github.com/meroxa/cli/issues/596
| 
|
|
|||

Update format of Resource Types list

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go

Early failure for deploying an application with a function to an env
Fixes https://github.com/meroxa/cli/issues/620
```
meroxa apps deploy --env aws     
✔ Checked your language is "ruby"
✔ Checked your application name is "test-rb"
Preparing to deploy application "test-rb"...
✔ Can access your Turbine resources
✔ Application processes found. Creating application image...
✔ Platform source fetched
✔ Dockerfile created
✔ "turbine-test-rb.tar.gz" successfully created in "/Users/dianadoherty/go/src/meroxa/test-rb"
✔ Source uploaded
✔ Removed "turbine-test-rb.tar.gz"
✔ Dockerfile removed
✔ Successfully built process image ("e8d91f4d-8a14-49a8-8213-3fb39d3fc370")
⠏ Deploying application "test-rb"... …
```

Early failure for deploying an application with a function to an env

---

cmd/meroxa/root/pipelines/create.go
cmd/meroxa/root/resources/create.go

Remove cli logic to handle common env for api
Fixes https://github.com/meroxa/cli/issues/623
```
meroxa resource create pg --type postgres --url  $PG_URL --env common 
Creating "postgres" resource in "common" environment...
Resource "pg" is successfully created!
```
```
meroxa resource create pg-c --type postgres --url $PG_URL --env common
Creating "postgres" resource in "common" environment...
Error: could not find environment. 1 detail reported:
1. type: "postgres"
```

Remove cli logic to handle common env for api

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go
cmd/meroxa/root/apps/errors.go
utils/tests.go

Turbine apps provisioned on env only supports resource which are part of these environments.
This change adds validation to ensure this is the case.
Minor refactor, rename method and ensure it returns errors rather than strings.
Create file to store error messages, it is a start.
Flatten bunch of obvious conditional paths.
Fixes #593
|||

Ensure turbine resource is in the same environment as the app

---

cmd/meroxa/builder/builder.go
cmd/meroxa/github/github.go

Acceptance tests failed because we didn't get a coherent response from brew.  Printing the upgrade message doesn't seem important enough to fail, so these changes just skip it and exit with no error instead.
|||
=== RUN   TestCollaborationsMySQLToPG/list_resource_types
shared_test.go:164: /app/bin/meroxa --cli-config-file /root/meroxa.main.env resources list --types
shared_test.go:166:      TYPES      
================
bigquery 
elasticsearch 
kafka 
mongodb 
mysql 
postgres 
redshift 
s3 
snowflakedb 
sqlserver 
notion 
confluentcloud 
panic: runtime error: index out of range [1] with length 0
goroutine 1 [running]:
github.com/meroxa/cli/cmd/meroxa/github.parseVersionFromFormulaFile({0x0, 0x0}) …

Ignore brew errors

---

cmd/meroxa/turbine/javascript/deploy.go

Fixes https://github.com/meroxa/turbine-js/issues/241
With this change, we're bumping the version of turbine-js that the CLI uses to manage Turbine apps.
Includes https://github.com/meroxa/turbine-js/pull/265
Includes https://github.com/meroxa/turbine-js/pull/242
Includes https://github.com/meroxa/turbine-js/pull/234

deps(turbine-js): bump turbine-js-cli to latest (v1.3.8)

---

Makefile
cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/list_test.go
cmd/meroxa/root/nop/nop.go
cmd/meroxa/turbine/golang/deploy.go
cmd/meroxa/turbine/golang/init.go
cmd/meroxa/turbine/javascript/build.go
cmd/meroxa/turbine/javascript/deploy.go
cmd/meroxa/turbine/javascript/upgrade.go
cmd/meroxa/turbine/local_deployment.go
cmd/meroxa/turbine/python/build.go
cmd/meroxa/turbine/python/deploy.go
cmd/meroxa/turbine/python/upgrade.go
cmd/meroxa/turbine/python/version.go
cmd/meroxa/turbine/ruby/build.go
cmd/meroxa/turbine/ruby/deploy.go
cmd/meroxa/turbine/ruby/init.go
cmd/meroxa/turbine/ruby/upgrade.go
cmd/meroxa/turbine/ruby/version.go
cmd/meroxa/turbine/utils.go
cmd/meroxa/turbine/utils_test.go
log/json.go
log/leveled.go
utils/display/apps_test.go
utils/tests.go

New linter version, new errors

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go

Passing env flag to CreateBuilds as part of functions + env changes. Env is needed for builds actions. 
Fixes https://github.com/meroxa/cli/issues/641

feat(apps): deploy support `--env`

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go

We want to consolidate source endpoints and always use v2 on application deploy. 
Fixes [<GitHub Issue>](https://github.com/meroxa/cli/issues/664)

Always use v2 Source endpoint on App Deploy

---

utils/display/resources.go

When the label is wrong, it will render  `%!s(<nil>)` .
|||

Ensure label exist and is `string` in resource types

---

cmd/meroxa/root/resources/create.go
cmd/meroxa/root/resources/create_test.go

Notion and Spire Maritime AIS require a token and not a URL, so be clear about the behavior
Fixes https://github.com/meroxa/cli/issues/676
BEFORE
AFTER

Warn users when --url value is ignored

---

cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go

Ensure environment exists when the `--env` flag is specified before the turbine deploy begins.
Fixes #621 
|||

Validate environment exists before turbine app is deployed

---

utils/display/resources.go
utils/display/resources_test.go

Customers should be able to find the flag value of a resource type that they have access to 
Fixes https://github.com/meroxa/cli/issues/685
|||
```shell
NAME            TYPE          RELEASE STAGE   
=============== =============== ===================
PostgreSQL      postgres        beta              
Google Sheets   google_sheets   developer_preview 
```

Also print accessible dev preview types in the Resource Types list

---

cmd/meroxa/root/apps/open.go
cmd/meroxa/root/apps/open_test.go

The test for `meroxa apps open` will open a browser every time the test is executed. The browser
step can be skipped, since that should be tested in the underlying library.
|||

Apps open should not open browser in tests

---

utils/display/environments.go

Fixes It also reuses the same function
**Before**
https://meroxa.slack.com/files/U01K6SFE06B/F058L7A0389/untitled
**After**
https://meroxa.slack.com/files/U01K6SFE06B/F05814EL18E/untitled
This is mostly because my IAM role lacks tons of permissions.

fix: environment preflights table

---

cmd/meroxa/turbine/python/run.go
cmd/meroxa/turbine/python/version.go

Small cleanup on python turbine related items, cleaning up error message, and we don't need to actually pass git-sha on run.

fix: cleanup turbine-py related items

---

cmd/meroxa/root/apps/apps.go
cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/deploy_test.go
cmd/meroxa/root/apps/errors.go
cmd/meroxa/root/apps/init.go
cmd/meroxa/root/apps/upgrade.go

This PR also refactors some of the error handling and app state detection.
```
m apps deploy
✔ Checked your language is "golang"
✔ Checked your application name is "filter-app"
✔ App "filter-app" is up-to-date
```
|||

Detect when same version of app has been deployed

---

cmd/meroxa/root/apps/deploy.go

Fixes an issue introduced by #753 where a missing deployment results in
```shell
> m apps deploy
✔ Checked your language is "golang"
✔ Checked your application name is "filter-app"
Error: could not find deployment
```
A missing deployment may be the result of an interrupted deployment due to build issues, if this does happen the app should be considered modified.
|||

Check for missing deployment

---

cmd/meroxa/root/flink/flink.go
cmd/meroxa/root/flink/remove.go
cmd/meroxa/root/flink/remove_test.go
utils/tests.go

Don't let the papi db get cluttered without a way to clean it up. 
Fixes https://github.com/meroxa/turbine-project/issues/291
|||

Command to delete flink jobs

---

cmd/meroxa/root/flink/flink.go
cmd/meroxa/root/flink/list.go
cmd/meroxa/root/flink/list_test.go
utils/display/flink_jobs.go
utils/display/flink_jobs_test.go

Fixes https://github.com/meroxa/turbine-project/issues/290
With this change, we're adding the `meroxa flink list` command to the CLI. This way, users will be able to see a list of their already deployed Flink jobs on the platform.
```
$ meroxa flink list
UUID                                    NAME              ENVIRONMENT       STATE             DEPLOYMENT STATE        
====================================== ================ ================== ================  ====================== 
118c7446-e60c-49a7-ac90-12e04d64df9e   my-first-flink       common           running           deployed                     
cb7a7d7c-8bb3-4549-9af7-4f9eaab9c2af   my-second-flink      common           failed            rolling back                
```

feat(flink): add command for listing flink jobs

---

cmd/meroxa/root/flink/describe.go
cmd/meroxa/root/flink/describe_test.go
cmd/meroxa/root/flink/flink.go
go.mod
go.sum
utils/display/flink_jobs.go
utils/display/flink_jobs_test.go
utils/tests.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/flink_job.go
vendor/modules.txt

Fixes https://github.com/meroxa/turbine-project/issues/289

feat(flink): Describe command for Flink Jobs

---

.github/workflows/ci.yml
.github/workflows/dispatch_turbine_go_dependency.yml
.github/workflows/fig.yml
.github/workflows/release.yml
.golangci.yml

Fixes CI errors on depguard. An alternative is disabled that check altogether...
**Before**
```
...
import 'github.com/fatih/color' is not allowed from list 'main' (depguard)
import 'github.com/briandowns/spinner' is not allowed from list 'main' (depguard)
import 'github.com/spf13/cobra' is not allowed from list 'main' (depguard)
import 'github.com/pkg/browser' is not allowed from list 'main' (depguard)
import 'github.com/spf13/cobra' is not allowed from list 'main' (depguard)
import 'github.com/spf13/cobra' is not allowed from list 'main' (depguard)
import 'github.com/spf13/cobra/doc' is not allowed from list 'main' (depguard)
import 'github.com/withfig/autocomplete-tools/integrations/cobra' is not allowed from list 'main' 
import 'github.com/gorilla/mux' is not allowed from list 'main' …
```

fix: depguard errors

---

go.mod
go.sum
utils/display/flink_jobs.go
utils/display/flink_jobs_test.go
vendor/github.com/meroxa/meroxa-go/pkg/meroxa/flink_job.go
vendor/modules.txt

Fixes https://github.com/meroxa/cli/issues/761
|||

feat(flink): Remove enum association from Flink Job state field

---

.github/workflows/ci.yml

None of the dependency updates are passing automation and automatically being merged. 
Related to https://github.com/meroxa/product/issues/595
|||

Dependabot automation failing with newer version of checkout

---

cmd/meroxa/turbine/golang/deploy.go
cmd/meroxa/turbine/golang/run.go
cmd/meroxa/turbine/javascript/deploy.go
cmd/meroxa/turbine/javascript/run.go
cmd/meroxa/turbine/python/deploy.go
cmd/meroxa/turbine/python/run.go
cmd/meroxa/turbine/ruby/deploy.go
cmd/meroxa/turbine/ruby/run.go

the process library may not detect all of the potential errors in the command it's running.  we need to look at stderr explicitly. 
Fixes https://github.com/meroxa/cli/issues/770
BEFORE
```shell
$ meroxa apps run
<_InactiveRpcError of RPC that terminated with:
status = StatusCode.UNKNOWN
details = "json: cannot unmarshal object into Go struct field fixtureRecord.Key of type string"
debug_error_string = "UNKNOWN:Error received from peer {created_time:"2023-06-08T16:49:06.304472766-07:00", grpc_status:2, grpc_message:"json: cannot unmarshal object into Go struct field fixtureRecord.Key of type string"}"
e(2023) janelle@janelle-thinkpad:~/go/src/github.com/meroxa/turbine-examples/python/notion-s3-python (restore-python-actions) $ echo $?
0 |
```
AFTER
```shell
$ m apps run
Error: …
```

Exit 1 when grpc requests fail

---

cmd/meroxa/turbine/golang/deploy.go
cmd/meroxa/turbine/golang/run.go
cmd/meroxa/turbine/javascript/deploy.go
cmd/meroxa/turbine/javascript/run.go
cmd/meroxa/turbine/python/deploy.go
cmd/meroxa/turbine/python/run.go
cmd/meroxa/turbine/ruby/deploy.go
cmd/meroxa/turbine/ruby/run.go
cmd/meroxa/turbine/utils.go
cmd/meroxa/turbine/utils_test.go
go.mod
go.sum
vendor/github.com/meroxa/turbine-core/pkg/app/config.go
vendor/modules.txt

Fixes https://github.com/meroxa/cli/issues/770
Related to https://github.com/meroxa/turbine-go/issues/162
BEFORE
```shell
$ meroxa apps run
<_InactiveRpcError of RPC that terminated with:
status = StatusCode.UNKNOWN
details = "json: cannot unmarshal object into Go struct field fixtureRecord.Key of type string"
debug_error_string = "UNKNOWN:Error received from peer {created_time:"2023-06-08T16:49:06.304472766-07:00", grpc_status:2, grpc_message:"json: cannot unmarshal object into Go struct field fixtureRecord.Key of type string"}"
e(2023) janelle@janelle-thinkpad:~/go/src/github.com/meroxa/turbine-examples/python/notion-s3-python (restore-python-actions) $ echo $?
0 |
```
AFTER
```shell
$ m apps run
Error: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.UNKNOWN
details …
```

Exit 1 when grpc requests fail (#771)

---

go.mod
go.sum
vendor/github.com/meroxa/turbine-core/pkg/server/internal/fixtures.go
vendor/modules.txt

The required JSON data format was not flexible to allow for a key that was not a string
Fixes https://github.com/meroxa/turbine-core/issues/153
|||

Pull in Notion bug fix

---

cmd/meroxa/turbine/golang/utils.go
go.mod
go.sum
vendor/github.com/meroxa/turbine-core/pkg/app/templates/golang/app.go
vendor/modules.txt

Must refer to turbine-go in a new way after proper v2 tagging
Related to meroxa/product#822
|||

Update references to turbine-go because of proper v2 tagging

---

.github/workflows/dispatch_turbine_go_dependency.yml
cmd/meroxa/turbine/golang/version.go

Turbine-go needs to be v2

---

cmd/meroxa/turbine/utils.go

Helps with making acceptance test errors clearer in particular
This affects run and deploy commands, in the least. 
BEFORE
```shell
=== RUN   TestAppMgmt/go:_Run_app
shared_test.go:174: C:\Users\runneradmin\go\bin\meroxa.exe --cli-config-file C:\Users\runneradmin/meroxa.main.env app run --path ../apps/turbine_go/template/tmp/app/go-acceptance-app-9bd2fb52-8670-41d6-b4b2-80011866f0b3 --json
shared_test.go:176: Error: exit status 1
```
AFTER
```shell
=== RUN   TestAppMgmt/go:_Run_app
shared_test.go:174: C:\Users\runneradmin\go\bin\meroxa.exe --cli-config-file C:\Users\runneradmin/meroxa.main.env app run --path ../apps/turbine_go/template/tmp/app/go-acceptance-app-9bd2fb52-8670-41d6-b4b2-80011866f0b3 --json
shared_test.go:176: Error: 2023/06/20 23:05:26 unable to find …
```

Add stdOut to error message so they are printed together

---

cmd/meroxa/root/flink/deploy.go

when the start and stop spinners don't line up, log lines get garbled
Fixes https://github.com/meroxa/product/issues/959
|
|
|

bug: use spinning logs correctly in flink deploy command

---

cmd/meroxa/turbine/utils.go

Adds more clarity to gRPC errors from turbine-core when an app has no sources defined.
Fixes https://github.com/meroxa/product/issues/936
```
❯ ../cli/meroxa apps deploy     
✔ Checked your language is "golang"
✔ Checked your application name is "notion-s3"
Error: 2023/08/07 14:13:23 rpc error: code = Unknown desc = invalid ProcessCollectionRequest.Collection: embedded message failed validation | caused by: invalid Collection.Name: value length must be at least 1 runes
exit status 1
```
```
❯ ../cli/meroxa apps deploy
✔ Checked your language is "golang"
✔ Checked your application name is "notion-s3"
Error: …
```

Clarify grpc errors for missing source collection

---

cmd/meroxa/turbine/golang/deploy.go
cmd/meroxa/turbine/golang/run.go
go.mod
go.sum
vendor/modules.txt

For Turbine Go, functions are always getting executed, regardless of which meroxa apps command is run (`meroxa apps run` and `meroxa apps deploy`)
We only want to execute the function during a `meroxa apps run`
Fixes https://github.com/meroxa/turbine-go/issues/162
Depends on: https://github.com/meroxa/turbine-go/pull/175

Fix function always getting executed for turbine go

---

.github/workflows/dispatch_turbine_go_dependency.yml

This updates branch references in the Turbine dependency update action to reference the new default branch name. 
|||

Change branch reference from master -> main

---

cmd/meroxa/global/basic_client.go
cmd/meroxa/global/config.go

Fixes the difference between doing requests via `api` commands and others using the Basic client.

fix: unify access token

---

cmd/meroxa/root/apps/apps.go
cmd/meroxa/root/apps/deploy.go
cmd/meroxa/root/apps/describe.go
cmd/meroxa/root/apps/describe_test.go
cmd/meroxa/root/apps/list.go
cmd/meroxa/root/apps/open.go
cmd/meroxa/root/apps/remove.go
cmd/meroxa/root/apps/remove_test.go
cmd/meroxa/root/root.go
cmd/meroxa/root/secrets/create.go
cmd/meroxa/root/secrets/create_test.go
cmd/meroxa/root/secrets/describe.go
cmd/meroxa/root/secrets/describe_test.go
cmd/meroxa/root/secrets/list.go
cmd/meroxa/root/secrets/list_test.go
cmd/meroxa/root/secrets/remove.go
cmd/meroxa/root/secrets/remove_test.go
cmd/meroxa/root/secrets/secrets.go
cmd/meroxa/root/secrets/update.go
utils/display/display.go

We want to be able to add, list, describe , remove and update secrets from CLI. 
Fixes https://github.com/meroxa/mdpx/issues/656
(In slack)

Add secrets command to CLI 
